#**USCIS Form Collection Pipeline**

This notebook crawls the USCIS Forms website, discovers publicly available form PDFs, downloads the documents, and genereates some metadata that is used by the document classification pipeline.

## Install + Import Required Libraries

In [ ]:
!pip install beautifulsoup4 requests lxml tqdm

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (6.1.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.6.17)

In [ ]:
import os
import requests

from bs4 import BeautifulSoup
from urllib.parse import urljoin
from tqdm import tqdm

## Configure + Test Crawler Settings

In [ ]:
USCIS_FORMS_URL = "https://www.uscis.gov/forms/all-forms"

print(USCIS_FORMS_URL)

https://www.uscis.gov/forms/all-forms

In [ ]:
response = requests.get(USCIS_FORMS_URL)

print(response.status_code)

200

In [ ]:
soup = BeautifulSoup(response.text, "lxml")

print(soup.title.text)

All Forms | USCIS

In [ ]:
links = soup.find_all("a", href=True)

print(f"Number of links found: {len(links)}")

Number of links found: 383

In [ ]:
form_links = []

for link in links:
    href = link["href"]

    if "forms" in href.lower():
        form_links.append(href)

print(f"Found {len(form_links)} links containing 'forms'\n")

for link in form_links[:50]:
    print(link)

Found 13 links containing 'forms'

/forms/forms
/forms/all-forms
/forms/explore-my-options
/forms/forms
/forms/all-forms
/forms/explore-my-options
/forms/filing-guidance
/forms/filing-fees
/forms/forms-updates
/forms/department-of-state-ds-and-other-non-uscis-forms
/forms/forms
https://www.uscis.gov/forms/all-forms/g-325r
/forms/forms

## Helper Functions

In [ ]:
import time
import requests

USER_AGENT = (
    "NewStartAI-Capstone-Crawler/0.1 "
    "(Educational Use)"
)

REQUEST_DELAY_SECONDS = 2

def polite_get(url):
    """
    Makes a respectful request to a website.
    """

    time.sleep(REQUEST_DELAY_SECONDS)

    response = requests.get(
        url,
        headers={"User-Agent": USER_AGENT},
        timeout=30
    )

    response.raise_for_status()

    return response

In [ ]:
response = polite_get("https://www.uscis.gov/forms/all-forms")

print(response.status_code)

200

In [ ]:
from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse
import re

In [ ]:
FORM_DETAIL_PATH_RE = re.compile(
    r"^/[a-z]{1,2}-\d+[a-z0-9]*$",
    re.IGNORECASE
)


def is_form_detail_path(path):
    return bool(FORM_DETAIL_PATH_RE.match(path))

In [ ]:
test_paths = [
    "/i-485",
    "/n-400",
    "/i-765",
    "/forms/all-forms",
    "/forms/filing-guidance",
    "/topics"
]


for path in test_paths:
    print(path, "->", is_form_detail_path(path))

/i-485 -> True
/n-400 -> True
/i-765 -> True
/forms/all-forms -> False
/forms/filing-guidance -> False
/topics -> False

In [ ]:
id="d2r6kd"
def find_form_detail_links(index_url):
    """
    Finds USCIS form-detail pages from the All Forms index page.
    """

    response = polite_get(index_url)

    soup = BeautifulSoup(response.text, "lxml")

    form_links = []

    for a in soup.find_all("a", href=True):

        href = a["href"]

        # Convert relative URLs into full URLs
        full_url = urljoin("https://www.uscis.gov", href)

        # Extract only the path portion
        path = urlparse(full_url).path

        # Keep only form pages
        if is_form_detail_path(path):
            form_links.append(full_url)

    # Remove duplicates while preserving order
    form_links = list(dict.fromkeys(form_links))

    return form_links

## Find USCIS Form Pages

The crawler begins at the USCIS "All Forms" page and identifies individual form pages that match the expected URL pattern.

In [ ]:
id="y2x3mf"
USCIS_FORMS_URL = "https://www.uscis.gov/forms/all-forms"

detail_links = find_form_detail_links(USCIS_FORMS_URL)

print(f"Found {len(detail_links)} form pages")

print("\nFirst 10:")
for link in detail_links[:10]:
    print(link)

Found 102 form pages

First 10:
https://www.uscis.gov/i-9
https://www.uscis.gov/i-485
https://www.uscis.gov/i-765
https://www.uscis.gov/i-90
https://www.uscis.gov/n-400
https://www.uscis.gov/i-129f
https://www.uscis.gov/i-130
https://www.uscis.gov/i-360
https://www.uscis.gov/i-600
https://www.uscis.gov/i-751

In [ ]:
def find_pdf_links(detail_url):
    """
    Finds PDF links on a USCIS form detail page.
    """

    response = polite_get(detail_url)

    soup = BeautifulSoup(response.text, "lxml")

    pdf_links = []

    for a in soup.find_all("a", href=True):

        href = a["href"]

        if href.lower().split("?")[0].endswith(".pdf"):

            full_url = urljoin(detail_url, href)

            pdf_links.append(full_url)

    # Remove duplicates
    pdf_links = list(dict.fromkeys(pdf_links))

    return pdf_links

In [ ]:
sample_form = "https://www.uscis.gov/i-485"

pdfs = find_pdf_links(sample_form)

print(f"Found {len(pdfs)} PDFs\n")

for pdf in pdfs:
    print(pdf)

Found 2 PDFs

https://www.uscis.gov/sites/default/files/document/forms/i-485.pdf
https://www.uscis.gov/sites/default/files/document/forms/i-485instr.pdf

## Collect PDF Links
Each form page is scanned for downloadable PDF documents including forms, instructions, supplements, and translated versions.

In [ ]:
def discover_all_pdf_links(form_pages):
    """
    Finds all PDF documents from all USCIS form pages.
    """

    all_pdfs = []

    for i, page in enumerate(form_pages):

        print(f"Processing {i+1}/{len(form_pages)}: {page}")

        pdfs = find_pdf_links(page)

        all_pdfs.extend(pdfs)

    # remove duplicates
    all_pdfs = list(dict.fromkeys(all_pdfs))

    return all_pdfs

In [ ]:
uscis_pdf_links = discover_all_pdf_links(detail_links)

print("\nTotal PDFs found:", len(uscis_pdf_links))

print("\nFirst 20 PDFs:")
for pdf in uscis_pdf_links[:20]:
    print(pdf)

Processing 1/102: https://www.uscis.gov/i-9
Processing 2/102: https://www.uscis.gov/i-485
Processing 3/102: https://www.uscis.gov/i-765
Processing 4/102: https://www.uscis.gov/i-90
Processing 5/102: https://www.uscis.gov/n-400
Processing 6/102: https://www.uscis.gov/i-129f
Processing 7/102: https://www.uscis.gov/i-130
Processing 8/102: https://www.uscis.gov/i-360
Processing 9/102: https://www.uscis.gov/i-600
Processing 10/102: https://www.uscis.gov/i-751
Processing 11/102: https://www.uscis.gov/i-129
Processing 12/102: https://www.uscis.gov/i-140
Processing 13/102: https://www.uscis.gov/i-526
Processing 14/102: https://www.uscis.gov/i-539
Processing 15/102: https://www.uscis.gov/i-589
Processing 16/102: https://www.uscis.gov/i-730
Processing 17/102: https://www.uscis.gov/i-821
Processing 18/102: https://www.uscis.gov/ar-11
Processing 19/102: https://www.uscis.gov/g-28
Processing 20/102: https://www.uscis.gov/g-28i
Processing 21/102: https://www.uscis.gov/g-325a
Processing 22/102: https://www.uscis.gov/g-325r
Processing 23/102: https://www.uscis.gov/g-845
Processing 24/102: https://www.uscis.gov/g-884
Processing 25/102: https://www.uscis.gov/g-1041
Processing 26/102: https://www.uscis.gov/g-1041a
Processing 27/102: https://www.uscis.gov/g-1055
Processing 28/102: https://www.uscis.gov/g-1145
Processing 29/102: https://www.uscis.gov/g-1256
Processing 30/102: https://www.uscis.gov/g-1450
Processing 31/102: https://www.uscis.gov/g-1566
Processing 32/102: https://www.uscis.gov/g-1650
Processing 33/102: https://www.uscis.gov/g-1651
Processing 34/102: https://www.uscis.gov/i-102
Processing 35/102: https://www.uscis.gov/i-129cw
Processing 36/102: https://www.uscis.gov/i-129cwr
Processing 37/102: https://www.uscis.gov/i-129s
Processing 38/102: https://www.uscis.gov/i-131
Processing 39/102: https://www.uscis.gov/i-131a
Processing 40/102: https://www.uscis.gov/i-134
Processing 41/102: https://www.uscis.gov/i-140g
Processing 42/102: https://www.uscis.gov/i-191
Processing 43/102: https://www.uscis.gov/i-192
Processing 44/102: https://www.uscis.gov/i-193
Processing 45/102: https://www.uscis.gov/i-212
Processing 46/102: https://www.uscis.gov/i-290b
Processing 47/102: https://www.uscis.gov/i-356
Processing 48/102: https://www.uscis.gov/i-361
Processing 49/102: https://www.uscis.gov/i-363
Processing 50/102: https://www.uscis.gov/i-407
Processing 51/102: https://www.uscis.gov/i-485supa
Processing 52/102: https://www.uscis.gov/i-485supj
Processing 53/102: https://www.uscis.gov/i-508
Processing 54/102: https://www.uscis.gov/i-526e
Processing 55/102: https://www.uscis.gov/i-566
Processing 56/102: https://www.uscis.gov/i-600a
Processing 57/102: https://www.uscis.gov/i-601
Processing 58/102: https://www.uscis.gov/i-601a
Processing 59/102: https://www.uscis.gov/i-602
Processing 60/102: https://www.uscis.gov/i-612
Processing 61/102: https://www.uscis.gov/i-687
Processing 62/102: https://www.uscis.gov/i-690
Processing 63/102: https://www.uscis.gov/i-693
Processing 64/102: https://www.uscis.gov/i-694
Processing 65/102: https://www.uscis.gov/i-698
Processing 66/102: https://www.uscis.gov/i-765v
Processing 67/102: https://www.uscis.gov/i-800
Processing 68/102: https://www.uscis.gov/i-800a
Processing 69/102: https://www.uscis.gov/i-817
Processing 70/102: https://www.uscis.gov/i-821d
Processing 71/102: https://www.uscis.gov/i-824
Processing 72/102: https://www.uscis.gov/i-829
Processing 73/102: https://www.uscis.gov/i-854
Processing 74/102: https://www.uscis.gov/i-864
Processing 75/102: https://www.uscis.gov/i-864a
Processing 76/102: https://www.uscis.gov/i-864ez
Processing 77/102: https://www.uscis.gov/i-864p
Processing 78/102: https://www.uscis.gov/i-865
Processing 79/102: https://www.uscis.gov/i-881
Processing 80/102: https://www.uscis.gov/i-905
Processing 81/102: https://www.uscis.gov/i-907
Processing 82/102: https://www.uscis.gov/i-910
Processing 83/102: https://www.uscis.gov/i-912
Processing 84/102: https://www.uscis.gov/i-914
Processing 85/102: https://www.uscis.gov/I-918
Processing 86/102: https://www.uscis.gov/i-929
Processing 87/102: https://www.uscis.gov/i-941
Processing 88/102: https://www.uscis.gov/i-945
Processing 89/102: https://www.uscis.gov/i-956
Processing 90/102: https://www.uscis.gov/i-956f
Processing 91/102: https://www.uscis.gov/i-956g
Processing 92/102: https://www.uscis.gov/i-956h
Processing 93/102: https://www.uscis.gov/i-956k
Processing 94/102: https://www.uscis.gov/n-300
Processing 95/102: https://www.uscis.gov/n-336
Processing 96/102: https://www.uscis.gov/n-426
Processing 97/102: https://www.uscis.gov/n-470
Processing 98/102: https://www.uscis.gov/n-565
Processing 99/102: https://www.uscis.gov/n-600
Processing 100/102: https://www.uscis.gov/n-600k
Processing 101/102: https://www.uscis.gov/n-644
Processing 102/102: https://www.uscis.gov/n-648

Total PDFs found: 281

First 20 PDFs:
https://www.uscis.gov/sites/default/files/document/forms/i-9.pdf
https://www.uscis.gov/sites/default/files/document/forms/i-9instr.pdf
https://www.uscis.gov/sites/default/files/document/forms/i-9-spanish.pdf
https://www.uscis.gov/sites/default/files/document/forms/i9-INS-Spanish.pdf
https://www.uscis.gov/sites/default/files/document/forms/i-485.pdf
https://www.uscis.gov/sites/default/files/document/forms/i-485instr.pdf
https://www.together.gov/assets/docs/Ms.%20L%20v.%20ICE%20Settlement.pdf
https://www.uscis.gov/sites/default/files/document/forms/i-765.pdf
https://www.uscis.gov/sites/default/files/document/forms/i-765instr.pdf
https://www.uscis.gov/sites/default/files/document/forms/i-765ws.pdf
https://www.uscis.gov/sites/default/files/document/notices/Applicant-Caused-Delays-in-Adjudications-of-Asylum-Applications-and-Impact-on-Employment-Authorization.pdf
https://www.uscis.gov/sites/default/files/document/forms/i-90.pdf
https://www.uscis.gov/sites/default/files/document/forms/i-90instr.pdf
https://www.uscis.gov/sites/default/files/document/forms/n-400.pdf
https://www.uscis.gov/sites/default/files/document/forms/n-400instr.pdf
https://www.uscis.gov/sites/default/files/document/guides/G-1151.pdf
https://www.uscis.gov/sites/default/files/document/questions-and-answers/Form-N400-FAQ-6-18-24.pdf
https://www.uscis.gov/sites/default/files/document/forms/i-129f.pdf
https://www.uscis.gov/sites/default/files/document/forms/i-129finstr.pdf
https://www.uscis.gov/sites/default/files/document/guides/K1_Process_V11.pdf

## Download USCIS PDFs
Download all discovered PDF documents

In [ ]:
import os
from pathlib import Path


DATA_DIR = Path("uscis_pdfs")

DATA_DIR.mkdir(exist_ok=True)


def download_pdf(url, save_dir=DATA_DIR):

    filename = url.split("/")[-1]

    filepath = save_dir / filename

    if filepath.exists():
        return filepath

    response = polite_get(url)

    with open(filepath, "wb") as f:
        f.write(response.content)

    return filepath

In [ ]:
sample_downloads = []

for url in uscis_pdf_links[:5]:

    path = download_pdf(url)
    sample_downloads.append(path)

    print("Downloaded:", path)

Downloaded: uscis_pdfs/i-9.pdf
Downloaded: uscis_pdfs/i-9instr.pdf
Downloaded: uscis_pdfs/i-9-spanish.pdf
Downloaded: uscis_pdfs/i9-INS-Spanish.pdf
Downloaded: uscis_pdfs/i-485.pdf

In [ ]:
from pathlib import Path

for file in Path("uscis_pdfs").iterdir():
    print(file.name, "----", file.stat().st_size/1024, "KB")

i-9instr.pdf ---- 290.0556640625 KB
i-9-spanish.pdf ---- 592.7978515625 KB
i9-INS-Spanish.pdf ---- 404.5537109375 KB
i-485.pdf ---- 1175.435546875 KB
i-9.pdf ---- 511.8115234375 KB

In [ ]:
!pip install pymupdf

Requirement already satisfied: pymupdf in /usr/local/lib/python3.12/dist-packages (1.28.0)

## Extract text
Opens pdf files and extracts the actual text from each file

In [ ]:
import fitz  # PyMuPDF


def extract_text(pdf_path):

    doc = fitz.open(pdf_path)

    text = ""

    for page in doc:
        text += page.get_text()

    return text


text = extract_text("uscis_pdfs/i-485.pdf")

print(text[:1000])

Form I-485   Edition   01/20/25
  Page 1 of 24
Section of Law
Application to Register Permanent Residence
or Adjust Status
Department of Homeland Security
U.S. Citizenship and Immigration Services
USCIS
Form I-485
 OMB No. 1615-0023
Expires 10/31/2027
Priority Date:
Country Chargeable:
INA 209(a)
INA 249
INA 245(a)
INA 245(i)
INA 245(m)
Sec. 13, Act of 9/11/57
Cuban Adjustment Act
Other
Lawful Permanent
Resident as of:
Date of
Initial Interview:
Action Block
Receipt
Interview
Waived
Applicant
Interviewed
Date Form I-693 Signed By Civil Surgeon:
Attorney State Bar Number
(if applicable)
Select this box if
Form G-28 is
attached.
Volag Number
(if any)
Attorney or Accredited Representative
USCIS Online Account Number (if any)
To be completed by an Attorney or Accredited Representative (if any).
For USCIS Use Only
START HERE - Type or print in black ink.
►
NOTE TO ALL APPLICANTS: If you do not completely fill out this application or fail to submit r

In [ ]:
import fitz
from pathlib import Path


def extract_text(pdf_path):
    """
    Extract text from a PDF using PyMuPDF.
    """

    try:
        doc = fitz.open(pdf_path)

        text = ""

        for page in doc:
            text += page.get_text()

        doc.close()

        return text.strip()

    except Exception as e:
        print(f"Error extracting {pdf_path}: {e}")
        return ""

In [ ]:
for pdf in Path("uscis_pdfs").iterdir():

    text = extract_text(pdf)

    print("\n----------------")
    print(pdf.name)
    print("Characters:", len(text))
    print(text[:200])

----------------
i-9instr.pdf
Characters: 29101
Page 1 of 8
Form I-9 Instructions   01/20/25
Instructions for Form I-9,
Employment Eligibility Verification
Department of Homeland Security
U.S. Citizenship and Immigration Ser

----------------
i-9-spanish.pdf
Characters: 16705
USCIS
Formulario I-9
OMB No. 1615-0047
Expire 05/31/2027
Verificación de Elegibilidad de Empleo
Departamento de Seguridad Nacional
Servicio de Ciudadanía e Inmigracion de Estados Unidos
COMIENCE

----------------
i9-INS-Spanish.pdf
Characters: 32247
Page 1 of 8
Form I-9 Instructions   01/20/25
Instrucciones para el Formulario I-9,
Verificación de Elegibilidad de Empleo
Departamento de Segurida

----------------
i-485.pdf
Characters: 54553
Form I-485   Edition   01/20/25
  Page 1 of 24
Section of Law
Application to Register Permanent Residence
or Adjust Status
Department of Homeland Security
U.S. Citizenship and Immigration Services

----------------
i-9.pdf
Characters: 14515
Employment Eligibility Verification
Department of Homeland Security
U.S. Citizenship and Immigration Services
USCIS
Form I-9
OMB No.1615-0047
Expires 05/31/2027
START HERE: Employers must ensure

In [ ]:
from pathlib import Path

for pdf in sorted(Path("uscis_pdfs").iterdir()):
    print(pdf.name)

i-485.pdf
i-9-spanish.pdf
i-9.pdf
i-9instr.pdf
i9-INS-Spanish.pdf

In [ ]:
from pathlib import Path

FULL_DATA_DIR = Path("uscis_all_pdfs")
FULL_DATA_DIR.mkdir(exist_ok=True)


def download_pdf(url, save_dir=FULL_DATA_DIR):

    filename = url.split("/")[-1]

    filepath = save_dir / filename

    if filepath.exists():
        return filepath

    response = polite_get(url)

    with open(filepath, "wb") as f:
        f.write(response.content)

    return filepath

In [ ]:
from urllib.parse import urlparse

def is_valid_uscis_form_pdf(url):
    parsed = urlparse(url)

    return (
        parsed.netloc.endswith("uscis.gov")
        and "/document/forms/" in parsed.path
        and parsed.path.lower().endswith(".pdf")
    )


filtered_uscis_pdf_links = [
    url for url in uscis_pdf_links
    if is_valid_uscis_form_pdf(url)
]

print("Before filtering:", len(uscis_pdf_links))
print("After filtering:", len(filtered_uscis_pdf_links))

filtered_uscis_pdf_links[:10]

Before filtering: 281
After filtering: 256

['https://www.uscis.gov/sites/default/files/document/forms/i-9.pdf',
 'https://www.uscis.gov/sites/default/files/document/forms/i-9instr.pdf',
 'https://www.uscis.gov/sites/default/files/document/forms/i-9-spanish.pdf',
 'https://www.uscis.gov/sites/default/files/document/forms/i9-INS-Spanish.pdf',
 'https://www.uscis.gov/sites/default/files/document/forms/i-485.pdf',
 'https://www.uscis.gov/sites/default/files/document/forms/i-485instr.pdf',
 'https://www.uscis.gov/sites/default/files/document/forms/i-765.pdf',
 'https://www.uscis.gov/sites/default/files/document/forms/i-765instr.pdf',
 'https://www.uscis.gov/sites/default/files/document/forms/i-765ws.pdf',
 'https://www.uscis.gov/sites/default/files/document/forms/i-90.pdf']

## Build Metadata
Metadata is used to describe each document from the filenames and is saved for processing down the line

In [ ]:
import pandas as pd
import re
from urllib.parse import urlparse


def extract_form_number(filename):
    """
    Extract USCIS form identifier.
    Examples:
    i-485.pdf -> I-485
    n-400instr.pdf -> N-400
    g-28.pdf -> G-28
    """

    match = re.match(r"([a-z]+-\d+)", filename.lower())

    if match:
        return match.group(1).upper()

    return None


def classify_document_type(filename):

    name = filename.lower()

    if "instr" in name:
        return "instructions"

    if "sup" in name:
        return "supplement"

    if "checklist" in name:
        return "checklist"

    if "spanish" in name or "es" in name:
        return "translated_form"

    return "form"


uscis_metadata = []

for url in filtered_uscis_pdf_links:

    filename = url.split("/")[-1]

    uscis_metadata.append({
        "filename": filename,
        "agency": "USCIS",
        "form_number": extract_form_number(filename),
        "document_type": classify_document_type(filename),
        "url": url
    })


uscis_df = pd.DataFrame(uscis_metadata)

uscis_df.head(10)

,filename,agency,form_number,document_type,url
0,i-9.pdf,USCIS,I-9,form,https://www.uscis.gov/sites/default/files/docu...
1,i-9instr.pdf,USCIS,I-9,instructions,https://www.uscis.gov/sites/default/files/docu...
2,i-9-spanish.pdf,USCIS,I-9,translated_form,https://www.uscis.gov/sites/default/files/docu...
3,i9-INS-Spanish.pdf,USCIS,None,translated_form,https://www.uscis.gov/sites/default/files/docu...
4,i-485.pdf,USCIS,I-485,form,https://www.uscis.gov/sites/default/files/docu...
5,i-485instr.pdf,USCIS,I-485,instructions,https://www.uscis.gov/sites/default/files/docu...
6,i-765.pdf,USCIS,I-765,form,https://www.uscis.gov/sites/default/files/docu...
7,i-765instr.pdf,USCIS,I-765,instructions,https://www.uscis.gov/sites/default/files/docu...
8,i-765ws.pdf,USCIS,I-765,form,https://www.uscis.gov/sites/default/files/docu...
9,i-90.pdf,USCIS,I-90,form,https://www.uscis.gov/sites/default/files/docu...

In [ ]:
uscis_df["document_type"].value_counts()

document_type
form               123
instructions       110
supplement          14
checklist            6
translated_form      3
Name: count, dtype: int64

In [ ]:
uscis_df["form_number"].value_counts().head(20)

form_number
I-589     26
I-129     12
I-601     10
I-956     10
I-800      8
I-600      7
I-864      6
I-485      6
I-914      5
I-918      5
I-765      5
I-526      4
I-140      4
I-821      4
G-1041     4
G-28       4
I-131      4
N-600      4
I-130      3
I-9        3
Name: count, dtype: int64

In [ ]:
uscis_df[uscis_df["form_number"].isin(
    ["I-589", "I-129", "I-601", "I-956"]
)][["filename","form_number","document_type"]]

                                    filename form_number    document_type
13                                i-129f.pdf       I-129             form
14                           i-129finstr.pdf       I-129     instructions
28                                 i-129.pdf       I-129             form
29                            i-129instr.pdf       I-129     instructions
30                              i-129h2a.pdf       I-129             form
31                         i-129h2ainstr.pdf       I-129     instructions
44                                 i-589.pdf       I-589             form
45                            i-589instr.pdf       I-589     instructions
46    I-589%20Form%20with%20Watermark_AR.pdf       I-589             form
47                I-589%20Instruction_AR.pdf       I-589     instructions
48    I-589%20Form%20with%20Watermark_CH.pdf       I-589             form
49               I-589%20Instructions_CH.pdf       I-589     instructions
50   I-589%20Form%20with%20Watermark_DAR.pdf       I-589             form
51              I-589%20Instructions_DAR.pdf       I-589     instructions
52    I-589%20Form%20with%20Watermark_FR.pdf       I-589             form
53               I-589%20Instructions_FR.pdf       I-589     instructions
54    I-589%20Form%20with%20Watermark_HC.pdf       I-589             form
55               I-589%20Instructions_HC.pdf       I-589     instructions
56   I-589%20Form%20with%20Watermark_PSH.pdf       I-589             form
57              I-589%20Instructions_PSH.pdf       I-589     instructions
58    I-589%20Form%20with%20Watermark_PT.pdf       I-589             form
59               I-589%20Instructions_PT.pdf       I-589     instructions
60    I-589%20Form%20with%20Watermark_RU.pdf       I-589             form
61               I-589%20Instructions_RU.pdf       I-589     instructions
62    I-589%20Form%20with%20Watermark_SO.pdf       I-589             form
63               I-589%20Instructions_SO.pdf       I-589     instructions
64   I-589%20Form%20with%20Watermark_TUR.pdf       I-589             form
65              I-589%20Instructions_TUR.pdf       I-589     instructions
66    I-589%20Form%20with%20Watermark_VI.pdf       I-589             form
67               I-589%20Instructions_VI.pdf       I-589     instructions
68    I-589%20Form%20with%20Watermark_ES.pdf       I-589  translated_form
69               I-589%20Instructions_ES.pdf       I-589     instructions
104                              i-129cw.pdf       I-129             form
105                         i-129cwinstr.pdf       I-129     instructions
106                             i-129cwr.pdf       I-129             form
107                        i-129cwrinstr.pdf       I-129     instructions
108                               i-129s.pdf       I-129             form
109                          i-129sinstr.pdf       I-129     instructions
147                                i-601.pdf       I-601             form
148                           i-601instr.pdf       I-601     instructions
149                               i-601a.pdf       I-601             form
150                          i-601ainstr.pdf       I-601     instructions
151              i-601achecklist_english.pdf       I-601        checklist
152              i-601achecklist_spanish.pdf       I-601        checklist
153                 i-601achecklist_viet.pdf       I-601        checklist
154           i-601achecklist_simchinese.pdf       I-601        checklist
155                  i-601achecklist_kor.pdf       I-601        checklist
156                 i-601achecklist_arab.pdf       I-601        checklist
227                                i-956.pdf       I-956             form
228                           i-956instr.pdf       I-956     instructions
229                          i-956finstr.pdf       I-956     instructions
230                               i-956f.pdf       I-956             form
231                          i-956ginstr.pdf       I-956     instructions
232                               i-956g.pdf       I-956             form
233                               i-956h.pdf       I-956             form
234                          i-956hinstr.pdf       I-956     instructions
235                               i-956k.pdf       I-956             form
236                          i-956kinstr.pdf       I-956     instructions

In [ ]:
uscis_df.to_csv("uscis_metadata.csv", index=False)

print("Saved:", len(uscis_df), "rows")

Saved: 256 rows

## Export Dataset

In [ ]:
import shutil
from pathlib import Path

source = Path("/content/uscis_pdfs")

destination = Path("/content/drive/MyDrive/newstart_ai/data/raw/uscis")

destination.mkdir(parents=True, exist_ok=True)


for file in source.glob("*.pdf"):
    shutil.copy(file, destination / file.name)

print("Copied USCIS PDFs:", len(list(destination.glob("*.pdf"))))

Copied USCIS PDFs: 5

In [ ]:
from pathlib import Path

uscis_drive = Path("/content/drive/MyDrive/newstart_ai/data/raw/uscis")

for file in uscis_drive.glob("*.pdf"):
    file.unlink()

print("Remaining USCIS files:", len(list(uscis_drive.glob("*.pdf"))))

Remaining USCIS files: 0

In [ ]:
from pathlib import Path

uscis_download_dir = Path("/content/uscis_pdfs")

# Clear old test downloads
for file in uscis_download_dir.glob("*.pdf"):
    file.unlink()

downloaded_files = []

for i, url in enumerate(filtered_uscis_pdf_links):

    try:
        path = download_pdf(url)
        downloaded_files.append(path)
        print(f"{i+1}/{len(filtered_uscis_pdf_links)} downloaded: {Path(path).name}")

    except Exception as e:
        print(f"FAILED: {url}")
        print(e)

print("\nDownload complete")
print("Downloaded:", len(downloaded_files))

1/256 downloaded: i-9.pdf
2/256 downloaded: i-9instr.pdf
3/256 downloaded: i-9-spanish.pdf
4/256 downloaded: i9-INS-Spanish.pdf
5/256 downloaded: i-485.pdf
6/256 downloaded: i-485instr.pdf
7/256 downloaded: i-765.pdf
8/256 downloaded: i-765instr.pdf
9/256 downloaded: i-765ws.pdf
10/256 downloaded: i-90.pdf
11/256 downloaded: i-90instr.pdf
12/256 downloaded: n-400.pdf
13/256 downloaded: n-400instr.pdf
14/256 downloaded: i-129f.pdf
15/256 downloaded: i-129finstr.pdf
16/256 downloaded: i-130.pdf
17/256 downloaded: i-130instr.pdf
18/256 downloaded: i-130a.pdf
19/256 downloaded: i-360.pdf
20/256 downloaded: i-360instr.pdf
21/256 downloaded: m-737.pdf
22/256 downloaded: i-600.pdf
23/256 downloaded: i-600instr.pdf
24/256 downloaded: i-600asup1.pdf
25/256 downloaded: i-600asup2.pdf
26/256 downloaded: i-600asup3.pdf
27/256 downloaded: i-751.pdf
28/256 downloaded: i-751instr.pdf
29/256 downloaded: i-129.pdf
30/256 downloaded: i-129instr.pdf
31/256 downloaded: i-129h2a.pdf
32/256 downloaded: i-129h2ainstr.pdf
33/256 downloaded: m-735.pdf
34/256 downloaded: m-1097.pdf
35/256 downloaded: m-1087.pdf
36/256 downloaded: m-736.pdf
37/256 downloaded: m-746.pdf
38/256 downloaded: i-140.pdf
39/256 downloaded: i-140instr.pdf
40/256 downloaded: i-526.pdf
41/256 downloaded: i-526instr.pdf
42/256 downloaded: i-539instr.pdf
43/256 downloaded: i-539.pdf
44/256 downloaded: i-539a.pdf
45/256 downloaded: i-589.pdf
46/256 downloaded: i-589instr.pdf
47/256 downloaded: I-589%20Form%20with%20Watermark_AR.pdf
48/256 downloaded: I-589%20Instruction_AR.pdf
49/256 downloaded: I-589%20Form%20with%20Watermark_CH.pdf
50/256 downloaded: I-589%20Instructions_CH.pdf
51/256 downloaded: I-589%20Form%20with%20Watermark_DAR.pdf
52/256 downloaded: I-589%20Instructions_DAR.pdf
53/256 downloaded: I-589%20Form%20with%20Watermark_FR.pdf
54/256 downloaded: I-589%20Instructions_FR.pdf
55/256 downloaded: I-589%20Form%20with%20Watermark_HC.pdf
56/256 downloaded: I-589%20Instructions_HC.pdf
57/256 downloaded: I-589%20Form%20with%20Watermark_PSH.pdf
58/256 downloaded: I-589%20Instructions_PSH.pdf
59/256 downloaded: I-589%20Form%20with%20Watermark_PT.pdf
60/256 downloaded: I-589%20Instructions_PT.pdf
61/256 downloaded: I-589%20Form%20with%20Watermark_RU.pdf
62/256 downloaded: I-589%20Instructions_RU.pdf
63/256 downloaded: I-589%20Form%20with%20Watermark_SO.pdf
64/256 downloaded: I-589%20Instructions_SO.pdf
65/256 downloaded: I-589%20Form%20with%20Watermark_TUR.pdf
66/256 downloaded: I-589%20Instructions_TUR.pdf
67/256 downloaded: I-589%20Form%20with%20Watermark_VI.pdf
68/256 downloaded: I-589%20Instructions_VI.pdf
69/256 downloaded: I-589%20Form%20with%20Watermark_ES.pdf
70/256 downloaded: I-589%20Instructions_ES.pdf
71/256 downloaded: i-730instr.pdf
72/256 downloaded: i-730.pdf
73/256 downloaded: i-590.pdf
74/256 downloaded: i-821.pdf
75/256 downloaded: i-821instr.pdf
76/256 downloaded: ar-11.pdf
77/256 downloaded: g-28.pdf
78/256 downloaded: g-28instr.pdf
79/256 downloaded: g-28i.pdf
80/256 downloaded: g-28iinstr.pdf
81/256 downloaded: g-325a.pdf
82/256 downloaded: g-325ainstr.pdf
83/256 downloaded: g-325r.pdf
84/256 downloaded: g-845.pdf
85/256 downloaded: g-845instr.pdf
86/256 downloaded: g-884.pdf
87/256 downloaded: g-884instr.pdf
88/256 downloaded: g-1041.pdf
89/256 downloaded: g-1041instr.pdf
90/256 downloaded: g-1041a.pdf
91/256 downloaded: g-1041ainstr.pdf
92/256 downloaded: g-1055.pdf
93/256 downloaded: g-1145.pdf
94/256 downloaded: g-1256.pdf
95/256 downloaded: g-1256instr.pdf
96/256 downloaded: g-1450.pdf
97/256 downloaded: g-1450instr.pdf
98/256 downloaded: g-1566.pdf
99/256 downloaded: g-1566instr.pdf
100/256 downloaded: g-1650.pdf
101/256 downloaded: g-1650instr.pdf
102/256 downloaded: g-1651.pdf
103/256 downloaded: i-102.pdf
104/256 downloaded: i-102instr.pdf
105/256 downloaded: i-129cw.pdf
106/256 downloaded: i-129cwinstr.pdf
107/256 downloaded: i-129cwr.pdf
108/256 downloaded: i-129cwrinstr.pdf
109/256 downloaded: i-129s.pdf
110/256 downloaded: i-129sinstr.pdf
111/256 downloaded: i-131.pdf
112/256 downloaded: i-131instr.pdf
113/256 downloaded: i-131a.pdf
114/256 downloaded: i-131ainstr.pdf
115/256 downloaded: i-134.pdf
116/256 downloaded: i-134instr.pdf
117/256 downloaded: i-140g.pdf
118/256 downloaded: I-140Ginstr.pdf
119/256 downloaded: i-191.pdf
120/256 downloaded: i-191instr.pdf
121/256 downloaded: i-192.pdf
122/256 downloaded: i-192instr.pdf
123/256 downloaded: i-193.pdf
124/256 downloaded: i-212.pdf
125/256 downloaded: i-212instr.pdf
126/256 downloaded: i-290b.pdf
127/256 downloaded: i-290binstr.pdf
128/256 downloaded: i-356.pdf
129/256 downloaded: i-356instr.pdf
130/256 downloaded: i-361.pdf
131/256 downloaded: i-361instr.pdf
132/256 downloaded: i-363.pdf
133/256 downloaded: i-363instr.pdf
134/256 downloaded: i-407.pdf
135/256 downloaded: i407instr.pdf
136/256 downloaded: i-485supa.pdf
137/256 downloaded: i-485supainstr.pdf
138/256 downloaded: i-485supj.pdf
139/256 downloaded: i-485supjinstr.pdf
140/256 downloaded: i-508.pdf
141/256 downloaded: i-508instr.pdf
142/256 downloaded: i-526e.pdf
143/256 downloaded: i-526einstr.pdf
144/256 downloaded: i-566.pdf
145/256 downloaded: i-566instr.pdf
146/256 downloaded: i-600a.pdf
147/256 downloaded: i-600ainstr.pdf
148/256 downloaded: i-601.pdf
149/256 downloaded: i-601instr.pdf
150/256 downloaded: i-601a.pdf
151/256 downloaded: i-601ainstr.pdf
152/256 downloaded: i-601achecklist_english.pdf
153/256 downloaded: i-601achecklist_spanish.pdf
154/256 downloaded: i-601achecklist_viet.pdf
155/256 downloaded: i-601achecklist_simchinese.pdf
156/256 downloaded: i-601achecklist_kor.pdf
157/256 downloaded: i-601achecklist_arab.pdf
158/256 downloaded: i-602.pdf
159/256 downloaded: i-602instr.pdf
160/256 downloaded: i-612.pdf
161/256 downloaded: i-612instr.pdf
162/256 downloaded: i-687.pdf
163/256 downloaded: i-687instr.pdf
164/256 downloaded: i-690.pdf
165/256 downloaded: i-690instr.pdf
166/256 downloaded: i-690sup1.pdf
167/256 downloaded: i-693.pdf
168/256 downloaded: i-693instr.pdf
169/256 downloaded: i-694.pdf
170/256 downloaded: i-694instr.pdf
171/256 downloaded: i-698.pdf
172/256 downloaded: i-698instr.pdf
173/256 downloaded: i-765v.pdf
174/256 downloaded: i-765vinstr.pdf
175/256 downloaded: i-800.pdf
176/256 downloaded: i-800instr.pdf
177/256 downloaded: i-800sup1.pdf
178/256 downloaded: i-800a.pdf
179/256 downloaded: i-800ainstr.pdf
180/256 downloaded: i-800asup1.pdf
181/256 downloaded: i-800asup2.pdf
182/256 downloaded: i-800asup3.pdf
183/256 downloaded: i-817.pdf
184/256 downloaded: i-817instr.pdf
185/256 downloaded: i-821d.pdf
186/256 downloaded: i-821dinstr.pdf
187/256 downloaded: i-824.pdf
188/256 downloaded: i-824instr.pdf
189/256 downloaded: i-829.pdf
190/256 downloaded: i-829instr.pdf
191/256 downloaded: i-854a.pdf
192/256 downloaded: i-854b.pdf
193/256 downloaded: i-854instr.pdf
194/256 downloaded: i-864.pdf
195/256 downloaded: i-864instr.pdf
196/256 downloaded: I-864a.pdf
197/256 downloaded: i-864ainstr.pdf
198/256 downloaded: i-864ez.pdf
199/256 downloaded: i-864ezinstr.pdf
200/256 downloaded: i-865.pdf
201/256 downloaded: i-865instr.pdf
202/256 downloaded: i-881.pdf
203/256 downloaded: i-881instr.pdf
204/256 downloaded: i-905.pdf
205/256 downloaded: i-905instr.pdf
206/256 downloaded: i-907.pdf
207/256 downloaded: i-907instr.pdf
208/256 downloaded: i-910.pdf
209/256 downloaded: i-910instr.pdf
210/256 downloaded: i-912.pdf
211/256 downloaded: i-912instr.pdf
212/256 downloaded: i-914.pdf
213/256 downloaded: i-914instr.pdf
214/256 downloaded: i-914supa.pdf
215/256 downloaded: i-914supb.pdf
216/256 downloaded: i-914supbinstr.pdf
217/256 downloaded: i-918.pdf
218/256 downloaded: i-918instr.pdf
219/256 downloaded: i-918supa.pdf
220/256 downloaded: i-918supb.pdf
221/256 downloaded: i-918supbinstr.pdf
222/256 downloaded: i-929.pdf
223/256 downloaded: i-929instr.pdf
224/256 downloaded: i-941.pdf
225/256 downloaded: i-941instr.pdf
226/256 downloaded: i-945.pdf
227/256 downloaded: i-945instr.pdf
228/256 downloaded: i-956.pdf
229/256 downloaded: i-956instr.pdf
230/256 downloaded: i-956finstr.pdf
231/256 downloaded: i-956f.pdf
232/256 downloaded: i-956ginstr.pdf
233/256 downloaded: i-956g.pdf
234/256 downloaded: i-956h.pdf
235/256 downloaded: i-956hinstr.pdf
236/256 downloaded: i-956k.pdf
237/256 downloaded: i-956kinstr.pdf
238/256 downloaded: n-300.pdf
239/256 downloaded: n-300instr.pdf
240/256 downloaded: n-336.pdf
241/256 downloaded: n-336instr.pdf
242/256 downloaded: n-426.pdf
243/256 downloaded: n-426instr.pdf
244/256 downloaded: m-599.pdf
245/256 downloaded: n-470.pdf
246/256 downloaded: n-470instr.pdf
247/256 downloaded: n-565.pdf
248/256 downloaded: n-565instr.pdf
249/256 downloaded: n-600.pdf
250/256 downloaded: n-600instr.pdf
251/256 downloaded: n-600k.pdf
252/256 downloaded: n-600kinstr.pdf
253/256 downloaded: n-644.pdf
254/256 downloaded: n-644instr.pdf
255/256 downloaded: n-648.pdf
256/256 downloaded: n-648instr.pdf

Download complete
Downloaded: 256

In [ ]:
import shutil
from pathlib import Path

source = Path("/content/uscis_all_pdfs")

destination = Path("/content/drive/MyDrive/newstart_ai/data/raw/uscis")

destination.mkdir(parents=True, exist_ok=True)

for file in source.glob("*.pdf"):
    shutil.copy(file, destination / file.name)

print(
    "Copied USCIS PDFs:",
    len(list(destination.glob("*.pdf")))
)

Copied USCIS PDFs: 256

In [ ]:
uscis_df.to_csv(
    "/content/drive/MyDrive/newstart_ai/data/raw/uscis_metadata.csv",
    index=False
)

print("Saved USCIS metadata")

Saved USCIS metadata

In [ ]:
import pandas as pd
from pathlib import Path
import re


# Folder where your USCIS PDFs are stored
uscis_folder = Path("/content/uscis_all_pdfs")


def extract_form_number(filename):
    """
    Extract USCIS form number.
    Examples:
    i-485.pdf -> I-485
    n-400.pdf -> N-400
    g-28.pdf -> G-28
    """

    match = re.match(r"([a-z]+-\d+)", filename.lower())

    if match:
        return match.group(1).upper()

    return None


def classify_document_type(filename):

    name = filename.lower()

    if "instr" in name:
        return "instructions"

    if "sup" in name:
        return "supplement"

    if "checklist" in name:
        return "checklist"

    if "spanish" in name or "es" in name:
        return "translated_form"

    return "form"


uscis_metadata = []


for pdf in uscis_folder.glob("*.pdf"):

    filename = pdf.name

    uscis_metadata.append({
        "filename": filename,
        "agency": "USCIS",
        "form_number": extract_form_number(filename),
        "document_type": classify_document_type(filename),
        "filepath": str(pdf)
    })


uscis_df = pd.DataFrame(uscis_metadata)


# Save CSV
uscis_df.to_csv(
    "uscis_metadata.csv",
    index=False
)


print("USCIS metadata saved!")
print("Rows:", len(uscis_df))

uscis_df.head()

USCIS metadata saved!
Rows: 256

,filename,agency,form_number,document_type,filepath
0,i-765ws.pdf,USCIS,I-765,form,/content/uscis_all_pdfs/i-765ws.pdf
1,i-361instr.pdf,USCIS,I-361,instructions,/content/uscis_all_pdfs/i-361instr.pdf
2,i-508instr.pdf,USCIS,I-508,instructions,/content/uscis_all_pdfs/i-508instr.pdf
3,g-1566instr.pdf,USCIS,G-1566,instructions,/content/uscis_all_pdfs/g-1566instr.pdf
4,i-129s.pdf,USCIS,I-129,form,/content/uscis_all_pdfs/i-129s.pdf

In [ ]:
from pathlib import Path

raw = Path("/content/drive/MyDrive/newstart_ai/data/raw")

for folder in ["uscis", "dmv", "ssa", "irs"]:
    path = raw / folder

    print("\n", folder)
    print("Exists:", path.exists())

    if path.exists():
        print("PDF count:", len(list(path.glob("*.pdf"))))

 uscis
Exists: True
PDF count: 0

 dmv
Exists: True
PDF count: 277

 ssa
Exists: False

 irs
Exists: True
PDF count: 0

In [ ]:
import shutil
from pathlib import Path

source = Path("/content/uscis_all_pdfs")

destination = Path("/content/drive/MyDrive/newstart_ai/data/raw/uscis")

destination.mkdir(parents=True, exist_ok=True)

count = 0

for file in source.glob("*.pdf"):
    shutil.copy(file, destination / file.name)
    count += 1

print("Copied USCIS PDFs:", count)

Copied USCIS PDFs: 256

In [ ]:
import pandas as pd
import re
from pathlib import Path


uscis_folder = Path("/content/drive/MyDrive/newstart_ai/data/raw/uscis")


def extract_form_number(filename):
    """
    Extract USCIS form identifier.
    Examples:
    i-485.pdf -> I-485
    n-400instr.pdf -> N-400
    g-28.pdf -> G-28
    """

    match = re.match(r"([a-z]+-\d+)", filename.lower())

    if match:
        return match.group(1).upper()

    return None


def classify_document_type(filename):

    name = filename.lower()

    if "instr" in name:
        return "instructions"

    if "sup" in name:
        return "supplement"

    if "checklist" in name:
        return "checklist"

    if "spanish" in name or "es" in name:
        return "translated_form"

    return "form"


metadata = []

for pdf in uscis_folder.glob("*.pdf"):

    metadata.append({
        "filename": pdf.name,
        "filepath": str(pdf),
        "agency": "USCIS",
        "form_number": extract_form_number(pdf.name),
        "document_type": classify_document_type(pdf.name)
    })


uscis_df = pd.DataFrame(metadata)

uscis_df.head()

,filename,filepath,agency,form_number,document_type
0,i-765ws.pdf,/content/drive/MyDrive/newstart_ai/data/raw/us...,USCIS,I-765,form
1,i-361instr.pdf,/content/drive/MyDrive/newstart_ai/data/raw/us...,USCIS,I-361,instructions
2,i-508instr.pdf,/content/drive/MyDrive/newstart_ai/data/raw/us...,USCIS,I-508,instructions
3,g-1566instr.pdf,/content/drive/MyDrive/newstart_ai/data/raw/us...,USCIS,G-1566,instructions
4,i-129s.pdf,/content/drive/MyDrive/newstart_ai/data/raw/us...,USCIS,I-129,form

In [ ]:
metadata_folder = Path("/content/drive/MyDrive/newstart_ai/data/metadata")

metadata_folder.mkdir(parents=True, exist_ok=True)

In [ ]:
uscis_csv = metadata_folder / "uscis_metadata.csv"

uscis_df.to_csv(uscis_csv, index=False)

print("Saved:", uscis_csv)
print("Rows:", len(uscis_df))

Saved: /content/drive/MyDrive/newstart_ai/data/metadata/uscis_metadata.csv
Rows: 256