# **California DMV Form Collection Pipeline**
This notebook colelcts publicly available California DMV forms.

## Import Required Libraries
Import the libraries used for web requests, HTML parsing, file management, and metadata generation.

In [ ]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse
import re
import os
import time

## Configure Web Requests
These settings create a reusable request function that identifies our crawler with a browser style user agent and a short delay to avoid overwhelming the DMV site.

In [ ]:
HEADERS = {
    "User-Agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/137.0 Safari/537.36"
}

def polite_get(url):
    time.sleep(1)
    response = requests.get(url, headers=HEADERS, timeout=30)
    response.raise_for_status()
    return response

In [ ]:
def download_pdf(url, folder):

    os.makedirs(folder, exist_ok=True)

    filename = url.split("/")[-1].split("?")[0]

    path = os.path.join(folder, filename)

    response = polite_get(url)

    with open(path, "wb") as f:
        f.write(response.content)

    return path

## Explore the DMV Forms website
Before building the crawler, this section inspects the DMV Forms page to better understand its structure, available links, and how PDF documents are organized. This helped guide the implementation of the crawler later.

In [ ]:
DMV_URL = "https://www.dmv.ca.gov/portal/forms/"

response = polite_get(DMV_URL)

print(response.status_code)
print(response.url)
print(response.text[:500])

200
https://www.dmv.ca.gov/portal/forms/
<!DOCTYPE html>
<html lang="en-US" class="no-js" dir="ltr">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<script>(function(html){html.className = html.className.replace(/\bno-js\b/,'js')})(document.documentElement);</script>
<meta name='robots' content='index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1' />
	<script>
		var dataLayer = dataLayer || [];
		dataLayer.push({"task":"N\/A","funcType":"resource po

In [ ]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(response.text, "lxml")

links = soup.find_all("a", href=True)

print("Total links:", len(links))

for link in links[:30]:
    print(link["href"])

Total links: 79
#main
https://www.ca.gov/
/portal/
#js-site-header__main-nav
/portal/driver-licenses-identification-cards/real-id/
/portal/dmv-online/
#
/portal/mydmv
https://dmv.ca.gov/portal/vehicle-registration/
/portal/vehicle-registration/vehicle-registration-renewal/
/portal/vehicle-registration/new-registration/
/portal/vehicle-registration/online-replacement-sticker-or-registration-card/
/portal/vehicle-registration/insurance-requirements/suspended-vehicle-registration/
/portal/customer-service/records-request/online-vehicle-record-request/
/portal/vehicle-registration/license-plates-decals-and-placards/
https://dmv.ca.gov/portal/driver-licenses-identification-cards/
/portal/driver-licenses-identification-cards/driver-license-id-card-online-renewal/
/portal/driver-licenses-identification-cards/dl-id-online-app-edl-44/
/portal/driver-licenses-identification-cards/replace-your-driver-license-or-identification-dl-id-card/online-duplicate-driver-license-request/
/portal/california-mdl/
/portal/customer-service/records-request/online-driver-record-request/
https://dmv.ca.gov/portal/customer-service/payments-refunds/
/portal/customer-service/payments-refunds/
/portal/vehicle-registration/vehicle-registration-renewal/
/portal/vehicle-registration/insurance-requirements/suspended-vehicle-registration/
/portal/dmv-virtual-office/dishonored-check-payment/
/portal/vehicle-registration/registration-fees/vehicle-registration-fee-calculator/
/portal/shopping-cart/
https://dmv.ca.gov/portal/appointments/select-appointment-type
/portal/locations/

In [ ]:
sample_url = "https://www.dmv.ca.gov/portal/form/application-for-disabled-person-placard-or-plates-reg-195/"

response = polite_get(sample_url)

print(response.status_code)

soup = BeautifulSoup(response.text, "lxml")

pdfs = []

for a in soup.find_all("a", href=True):
    href = a["href"]
    if ".pdf" in href.lower():
        pdfs.append(href)

print(f"Found {len(pdfs)} PDFs")

for pdf in pdfs:
    print(pdf)

200
Found 0 PDFs

In [ ]:
links = soup.find_all("a", href=True)

print("Total links:", len(links))

for a in links:
    print(a["href"])

Total links: 0

In [ ]:
for a in soup.find_all("a", href=True):
    text = a.get_text(strip=True)
    if text:
        print(f"{text[:60]:60} -> {a['href']}")

In [ ]:
dmv_forms = []

for a in links:
    href = a["href"]

    if "/portal/form/" in href:
        dmv_forms.append(
            "https://www.dmv.ca.gov" + href
        )

print("Total DMV forms found:", len(dmv_forms))

for form in dmv_forms[:10]:
    print(form)

Total DMV forms found: 0

In [ ]:
DMV_FORMS_URL = "https://www.dmv.ca.gov/portal/forms/"

dmv_response = polite_get(DMV_FORMS_URL)

print(dmv_response.status_code)
print(dmv_response.headers.get("Content-Type"))

200
text/html; charset=UTF-8

In [ ]:
dmv_soup = BeautifulSoup(dmv_response.text, "lxml")

dmv_links = dmv_soup.find_all("a", href=True)

dmv_forms = []

for a in dmv_links:
    href = a["href"]

    if "/portal/form/" in href:
        full_url = urljoin("https://www.dmv.ca.gov", href)
        dmv_forms.append(full_url)

# remove duplicates
dmv_forms = list(dict.fromkeys(dmv_forms))

print("Total DMV forms found:", len(dmv_forms))

for form in dmv_forms[:20]:
    print(form)

Total DMV forms found: 16
https://www.dmv.ca.gov/portal/form/application-for-disabled-person-placard-or-plates-reg-195/
https://www.dmv.ca.gov/portal/form/application-for-replacement-or-transfer-of-title-reg-227/
https://www.dmv.ca.gov/portal/form/application-for-replacement-plates-stickers-documents-reg-156/
https://www.dmv.ca.gov/portal/form/application-for-title-or-registration-verification-of-vehicle-reg-343/
https://www.dmv.ca.gov/portal/form/bill-of-sale-reg-135-pdf/
https://www.dmv.ca.gov/portal/form/statement-of-facts-reg-256/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-english-adm-140/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-armenian-adm-140/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-chinese-adm-140-ch/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-farsi-adm-140-fa/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-punjabi-adm-14/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-russian-adm-140-ru/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-spanish-adm-140sp/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-tagalog-adm-140/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-vietnamese-adm-140/
https://www.dmv.ca.gov/portal/form/application-for-refund-adm-399/

## Build the Form Discovery Process
After understanding the website, these helper functions were made to find DMV form pages throughout the website.

In [ ]:
from urllib.parse import urljoin

BASE_DMV = "https://www.dmv.ca.gov"

def find_dmv_forms(page_url):
    response = polite_get(page_url)
    soup = BeautifulSoup(response.text, "lxml")

    forms = []

    for a in soup.find_all("a", href=True):
        href = a["href"]

        if "/portal/form/" in href:
            forms.append(urljoin(BASE_DMV, href))

    return forms


all_dmv_forms = []

for page in range(1, 32):

    if page == 1:
        url = "https://www.dmv.ca.gov/portal/forms/"
    else:
        url = f"https://www.dmv.ca.gov/portal/forms/page/{page}/"

    forms = find_dmv_forms(url)

    print(f"Page {page}: {len(forms)} forms")

    all_dmv_forms.extend(forms)


# remove duplicates
all_dmv_forms = list(dict.fromkeys(all_dmv_forms))


print("\nTotal unique DMV forms:", len(all_dmv_forms))

for form in all_dmv_forms[:20]:
    print(form)

Page 1: 16 forms
Page 2: 16 forms
Page 3: 16 forms
Page 4: 16 forms
Page 5: 16 forms
Page 6: 15 forms
Page 7: 16 forms
Page 8: 16 forms
Page 9: 16 forms
Page 10: 16 forms
Page 11: 16 forms
Page 12: 16 forms
Page 13: 16 forms
Page 14: 16 forms
Page 15: 16 forms
Page 16: 16 forms
Page 17: 16 forms
Page 18: 16 forms
Page 19: 16 forms
Page 20: 16 forms
Page 21: 16 forms
Page 22: 16 forms
Page 23: 16 forms
Page 24: 16 forms
Page 25: 15 forms
Page 26: 16 forms
Page 27: 16 forms
Page 28: 16 forms
Page 29: 16 forms
Page 30: 16 forms
Page 31: 12 forms

Total unique DMV forms: 305
https://www.dmv.ca.gov/portal/form/application-for-disabled-person-placard-or-plates-reg-195/
https://www.dmv.ca.gov/portal/form/application-for-replacement-or-transfer-of-title-reg-227/
https://www.dmv.ca.gov/portal/form/application-for-replacement-plates-stickers-documents-reg-156/
https://www.dmv.ca.gov/portal/form/application-for-title-or-registration-verification-of-vehicle-reg-343/
https://www.dmv.ca.gov/portal/form/bill-of-sale-reg-135-pdf/
https://www.dmv.ca.gov/portal/form/statement-of-facts-reg-256/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-english-adm-140/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-armenian-adm-140/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-chinese-adm-140-ch/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-farsi-adm-140-fa/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-punjabi-adm-14/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-russian-adm-140-ru/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-spanish-adm-140sp/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-tagalog-adm-140/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-vietnamese-adm-140/
https://www.dmv.ca.gov/portal/form/application-for-refund-adm-399/
https://www.dmv.ca.gov/portal/form/appointment-of-director-as-agent-for-service-of-process-adm-9050/
https://www.dmv.ca.gov/portal/form/historical-vessel-plaque/
https://www.dmv.ca.gov/portal/form/application-for-vessel-certificate-of-number-boat-101/
https://www.dmv.ca.gov/portal/form/application-for-boat-registration-number-dealer-manufacturer-boat-101a/

In [ ]:
for url in all_dmv_forms[:5]:
    response = polite_get(url)
    print(url, response.headers["Content-Type"])

https://www.dmv.ca.gov/portal/form/application-for-disabled-person-placard-or-plates-reg-195/ application/pdf
https://www.dmv.ca.gov/portal/form/application-for-replacement-or-transfer-of-title-reg-227/ application/pdf
https://www.dmv.ca.gov/portal/form/application-for-replacement-plates-stickers-documents-reg-156/ application/pdf
https://www.dmv.ca.gov/portal/form/application-for-title-or-registration-verification-of-vehicle-reg-343/ application/pdf
https://www.dmv.ca.gov/portal/form/bill-of-sale-reg-135-pdf/ application/pdf

## Crawl DMV Form Pages

Next the crawler iterates through every page of the DMV Forms directory, collects the links to forms, and removes duplicates.

In [ ]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin


BASE_URL = "https://www.dmv.ca.gov"
FORMS_URL = "https://www.dmv.ca.gov/portal/forms/"


def get_dmv_form_links():

    all_forms = set()

    page = 1

    while True:

        if page == 1:
            url = FORMS_URL
        else:
            url = f"{FORMS_URL}page/{page}/"

        response = requests.get(url)

        if response.status_code != 200:
            break

        soup = BeautifulSoup(response.text, "html.parser")

        page_forms = []

        for a in soup.find_all("a", href=True):

            href = a["href"]

            full_url = urljoin(BASE_URL, href)

            if "/portal/form/" in full_url:
                page_forms.append(full_url)


        page_forms = list(set(page_forms))


        if len(page_forms) == 0:
            break


        print(f"Page {page}: {len(page_forms)} forms")


        all_forms.update(page_forms)

        page += 1


    return sorted(all_forms)

In [ ]:
# there are clearly enough form s will cut short later
#dmv_forms = get_dmv_form_links()

#print("\nTotal:", len(dmv_forms))

Page 1: 16 forms
Page 2: 16 forms
Page 3: 16 forms
Page 4: 16 forms
Page 5: 16 forms
Page 6: 15 forms
Page 7: 16 forms
Page 8: 16 forms
Page 9: 16 forms
Page 10: 16 forms
Page 11: 16 forms
Page 12: 16 forms
Page 13: 16 forms
Page 14: 16 forms
Page 15: 16 forms
Page 16: 16 forms
Page 17: 16 forms
Page 18: 16 forms
Page 19: 16 forms
Page 20: 16 forms
Page 21: 16 forms
Page 22: 16 forms
Page 23: 15 forms
Page 24: 14 forms
Page 25: 14 forms
Page 26: 15 forms
Page 27: 16 forms
Page 28: 16 forms
Page 29: 16 forms
Page 30: 16 forms
Page 31: 12 forms
Page 32: 6 forms
Page 33: 6 forms
Page 34: 6 forms
Page 35: 6 forms
Page 36: 6 forms
Page 37: 6 forms
Page 38: 6 forms
Page 39: 6 forms
Page 40: 6 forms
Page 41: 6 forms
Page 42: 6 forms
Page 43: 6 forms
Page 44: 6 forms
Page 45: 6 forms
Page 46: 6 forms
Page 47: 6 forms
Page 48: 6 forms
Page 49: 6 forms
Page 50: 6 forms
Page 51: 6 forms
Page 52: 6 forms
Page 53: 6 forms
Page 54: 6 forms
Page 55: 6 forms
Page 56: 6 forms
Page 57: 6 forms
Page 58: 6 forms
Page 59: 6 forms
Page 60: 6 forms
Page 61: 6 forms
Page 62: 6 forms
Page 63: 6 forms
Page 64: 6 forms
Page 65: 6 forms
Page 66: 6 forms
Page 67: 6 forms
Page 68: 6 forms
Page 69: 6 forms
Page 70: 6 forms
Page 71: 6 forms
Page 72: 6 forms
Page 73: 6 forms
Page 74: 6 forms
Page 75: 6 forms
Page 76: 6 forms
Page 77: 6 forms
Page 78: 6 forms
Page 79: 6 forms
Page 80: 6 forms
Page 81: 6 forms
Page 82: 6 forms
Page 83: 6 forms
Page 84: 6 forms
Page 85: 6 forms
Page 86: 6 forms
Page 87: 6 forms
Page 88: 6 forms
Page 89: 6 forms
Page 90: 6 forms
Page 91: 6 forms
Page 92: 6 forms
Page 93: 6 forms
Page 94: 6 forms
Page 95: 6 forms
Page 96: 6 forms
Page 97: 6 forms
Page 98: 6 forms
Page 99: 6 forms
Page 100: 6 forms
Page 101: 6 forms
Page 102: 6 forms
Page 103: 6 forms
Page 104: 6 forms
Page 105: 6 forms
Page 106: 6 forms
Page 107: 6 forms
Page 108: 6 forms
Page 109: 6 forms
Page 110: 6 forms
Page 111: 6 forms
Page 112: 6 forms
Page 113: 6 forms
Page 114: 6 forms
Page 115: 6 forms
Page 116: 6 forms
Page 117: 6 forms
Page 118: 6 forms
Page 119: 6 forms
Page 120: 6 forms
Page 121: 6 forms
Page 122: 6 forms
Page 123: 6 forms
Page 124: 6 forms
Page 125: 6 forms
Page 126: 6 forms
Page 127: 6 forms
Page 128: 6 forms
Page 129: 6 forms
Page 130: 6 forms
Page 131: 6 forms
Page 132: 6 forms
Page 133: 6 forms
Page 134: 6 forms
Page 135: 6 forms
Page 136: 6 forms
Page 137: 6 forms
Page 138: 6 forms
Page 139: 6 forms
Page 140: 6 forms
Page 141: 6 forms
Page 142: 6 forms
Page 143: 6 forms
Page 144: 6 forms
Page 145: 6 forms
Page 146: 6 forms
Page 147: 6 forms
Page 148: 6 forms
Page 149: 6 forms
Page 150: 6 forms
Page 151: 6 forms
Page 152: 6 forms
Page 153: 6 forms
Page 154: 6 forms
Page 155: 6 forms
Page 156: 6 forms
Page 157: 6 forms
Page 158: 6 forms
Page 159: 6 forms
Page 160: 6 forms
Page 161: 6 forms
Page 162: 6 forms
Page 163: 6 forms
Page 164: 6 forms
Page 165: 6 forms
Page 166: 6 forms
Page 167: 6 forms
Page 168: 6 forms
Page 169: 6 forms
Page 170: 6 forms
Page 171: 6 forms
Page 172: 6 forms
Page 173: 6 forms
Page 174: 6 forms
Page 175: 6 forms
Page 176: 6 forms
Page 177: 6 forms
Page 178: 6 forms
Page 179: 6 forms
Page 180: 6 forms
Page 181: 6 forms
Page 182: 6 forms
Page 183: 6 forms
Page 184: 6 forms
Page 185: 6 forms
Page 186: 6 forms
Page 187: 6 forms
Page 188: 6 forms
Page 189: 6 forms
Page 190: 6 forms
Page 191: 6 forms
Page 192: 6 forms
Page 193: 6 forms
Page 194: 6 forms
Page 195: 6 forms
Page 196: 6 forms
Page 197: 6 forms
Page 198: 6 forms
Page 199: 6 forms
Page 200: 6 forms
Page 201: 6 forms
Page 202: 6 forms
Page 203: 6 forms
Page 204: 6 forms
Page 205: 6 forms
Page 206: 6 forms
Page 207: 6 forms
Page 208: 6 forms
Page 209: 6 forms
Page 210: 6 forms
Page 211: 6 forms
Page 212: 6 forms
Page 213: 6 forms
Page 214: 6 forms
Page 215: 6 forms
Page 216: 6 forms
Page 217: 6 forms
Page 218: 6 forms
Page 219: 6 forms
Page 220: 6 forms
Page 221: 6 forms
Page 222: 6 forms
Page 223: 6 forms
Page 224: 6 forms
Page 225: 6 forms
Page 226: 6 forms
Page 227: 6 forms
Page 228: 6 forms
Page 229: 6 forms
Page 230: 6 forms
Page 231: 6 forms
Page 232: 6 forms
Page 233: 6 forms
Page 234: 6 forms
Page 235: 6 forms
Page 236: 6 forms
Page 237: 6 forms
Page 238: 6 forms
Page 239: 6 forms
Page 240: 6 forms
Page 241: 6 forms
Page 242: 6 forms
Page 243: 6 forms
Page 244: 6 forms
Page 245: 6 forms
Page 246: 6 forms
Page 247: 6 forms
Page 248: 6 forms
Page 249: 6 forms
Page 250: 6 forms
Page 251: 6 forms
Page 252: 6 forms
Page 253: 6 forms
Page 254: 6 forms
Page 255: 6 forms
Page 256: 6 forms
Page 257: 6 forms
Page 258: 6 forms
Page 259: 6 forms
Page 260: 6 forms
Page 261: 6 forms
Page 262: 6 forms
Page 263: 6 forms
Page 264: 6 forms
Page 265: 6 forms
Page 266: 6 forms
Page 267: 6 forms
Page 268: 6 forms
Page 269: 6 forms
Page 270: 6 forms
Page 271: 6 forms
Page 272: 6 forms
Page 273: 6 forms
Page 274: 6 forms
Page 275: 6 forms
Page 276: 6 forms
Page 277: 6 forms
Page 278: 6 forms
Page 279: 6 forms
Page 280: 6 forms
Page 281: 6 forms
Page 282: 6 forms
Page 283: 6 forms
Page 284: 6 forms
Page 285: 6 forms
Page 286: 6 forms
Page 287: 6 forms
Page 288: 6 forms
Page 289: 6 forms
Page 290: 6 forms
Page 291: 6 forms
Page 292: 6 forms
Page 293: 6 forms
Page 294: 6 forms
Page 295: 6 forms
Page 296: 6 forms
Page 297: 6 forms
Page 298: 6 forms
Page 299: 6 forms
Page 300: 6 forms
Page 301: 6 forms
Page 302: 6 forms
Page 303: 6 forms
Page 304: 6 forms
Page 305: 6 forms
Page 306: 6 forms
Page 307: 6 forms
Page 308: 6 forms
Page 309: 6 forms
Page 310: 6 forms
Page 311: 6 forms
Page 312: 6 forms
Page 313: 6 forms
Page 314: 6 forms
Page 315: 6 forms
Page 316: 6 forms
Page 317: 6 forms
Page 318: 6 forms
Page 319: 6 forms
Page 320: 6 forms
Page 321: 6 forms
Page 322: 6 forms
Page 323: 6 forms
Page 324: 6 forms
Page 325: 6 forms
Page 326: 6 forms
Page 327: 6 forms
Page 328: 6 forms
Page 329: 6 forms
Page 330: 6 forms
Page 331: 6 forms
Page 332: 6 forms
Page 333: 6 forms
Page 334: 6 forms
Page 335: 6 forms
Page 336: 6 forms
Page 337: 6 forms
Page 338: 6 forms
Page 339: 6 forms
Page 340: 6 forms
Page 341: 6 forms
Page 342: 6 forms
Page 343: 6 forms
Page 344: 6 forms
Page 345: 6 forms
Page 346: 6 forms
Page 347: 6 forms
Page 348: 6 forms
Page 349: 6 forms
Page 350: 6 forms
Page 351: 6 forms
Page 352: 6 forms
Page 353: 6 forms
Page 354: 6 forms
Page 355: 6 forms
Page 356: 6 forms
Page 357: 6 forms
Page 358: 6 forms
Page 359: 6 forms
Page 360: 6 forms
Page 361: 6 forms
Page 362: 6 forms
Page 363: 6 forms
Page 364: 6 forms
Page 365: 6 forms
Page 366: 6 forms
Page 367: 6 forms
Page 368: 6 forms
Page 369: 6 forms
Page 370: 6 forms
Page 371: 6 forms
Page 372: 6 forms
Page 373: 6 forms
Page 374: 6 forms
Page 375: 6 forms
Page 376: 6 forms
Page 377: 6 forms
Page 378: 6 forms
Page 379: 6 forms
Page 380: 6 forms
Page 381: 6 forms
Page 382: 6 forms
Page 383: 6 forms
Page 384: 6 forms
Page 385: 6 forms
Page 386: 6 forms
Page 387: 6 forms
Page 388: 6 forms
Page 389: 6 forms
Page 390: 6 forms
Page 391: 6 forms
Page 392: 6 forms
Page 393: 6 forms
Page 394: 6 forms
Page 395: 6 forms
Page 396: 6 forms
Page 397: 6 forms
Page 398: 6 forms
Page 399: 6 forms
Page 400: 6 forms
Page 401: 6 forms
Page 402: 6 forms
Page 403: 6 forms
Page 404: 6 forms
Page 405: 6 forms
Page 406: 6 forms
Page 407: 6 forms
Page 408: 6 forms
Page 409: 6 forms
Page 410: 6 forms
Page 411: 6 forms
Page 412: 6 forms
Page 413: 6 forms
Page 414: 6 forms
Page 415: 6 forms
Page 416: 6 forms
Page 417: 6 forms
Page 418: 6 forms
Page 419: 6 forms
Page 420: 6 forms
Page 421: 6 forms
Page 422: 6 forms
Page 423: 6 forms
Page 424: 6 forms
Page 425: 6 forms
Page 426: 6 forms
Page 427: 6 forms
Page 428: 6 forms
Page 429: 6 forms
Page 430: 6 forms
Page 431: 6 forms
Page 432: 6 forms
Page 433: 6 forms
Page 434: 6 forms
Page 435: 6 forms
Page 436: 6 forms
Page 437: 6 forms
Page 438: 6 forms
Page 439: 6 forms
Page 440: 6 forms
Page 441: 6 forms
Page 442: 6 forms
Page 443: 6 forms
Page 444: 6 forms
Page 445: 6 forms
Page 446: 6 forms
Page 447: 6 forms
Page 448: 6 forms
Page 449: 6 forms
Page 450: 6 forms
Page 451: 6 forms
Page 452: 6 forms
Page 453: 6 forms
Page 454: 6 forms
Page 455: 6 forms
Page 456: 6 forms
Page 457: 6 forms
Page 458: 6 forms
Page 459: 6 forms
Page 460: 6 forms
Page 461: 6 forms
Page 462: 6 forms
Page 463: 6 forms
Page 464: 6 forms
Page 465: 6 forms
Page 466: 6 forms
Page 467: 6 forms
Page 468: 6 forms
Page 469: 6 forms
Page 470: 6 forms
Page 471: 6 forms
Page 472: 6 forms
Page 473: 6 forms
Page 474: 6 forms
Page 475: 6 forms
Page 476: 6 forms
Page 477: 6 forms
Page 478: 6 forms
Page 479: 6 forms
Page 480: 6 forms
Page 481: 6 forms
Page 482: 6 forms
Page 483: 6 forms
Page 484: 6 forms
Page 485: 6 forms
Page 486: 6 forms
Page 487: 6 forms
Page 488: 6 forms
Page 489: 6 forms
Page 490: 6 forms
Page 491: 6 forms
Page 492: 6 forms
Page 493: 6 forms
Page 494: 6 forms
Page 495: 6 forms
Page 496: 6 forms
Page 497: 6 forms
Page 498: 6 forms
Page 499: 6 forms
Page 500: 6 forms
Page 501: 6 forms
Page 502: 6 forms
Page 503: 6 forms
Page 504: 6 forms
Page 505: 6 forms
Page 506: 6 forms
Page 507: 6 forms
Page 508: 6 forms
Page 509: 6 forms
Page 510: 6 forms
Page 511: 6 forms
Page 512: 6 forms
Page 513: 6 forms
Page 514: 6 forms
Page 515: 6 forms
Page 516: 6 forms
Page 517: 6 forms
Page 518: 6 forms
Page 519: 6 forms
Page 520: 6 forms
Page 521: 6 forms
Page 522: 6 forms
Page 523: 6 forms
Page 524: 6 forms
Page 525: 6 forms
Page 526: 6 forms
Page 527: 6 forms
Page 528: 6 forms
Page 529: 6 forms
Page 530: 6 forms
Page 531: 6 forms
Page 532: 6 forms
Page 533: 6 forms
Page 534: 6 forms
Page 535: 6 forms
Page 536: 6 forms
Page 537: 6 forms
Page 538: 6 forms
Page 539: 6 forms
Page 540: 6 forms
Page 541: 6 forms
Page 542: 6 forms
Page 543: 6 forms
Page 544: 6 forms
Page 545: 6 forms
Page 546: 6 forms
Page 547: 6 forms
Page 548: 6 forms
Page 549: 6 forms
Page 550: 6 forms
Page 551: 6 forms
Page 552: 6 forms
Page 553: 6 forms
Page 554: 6 forms
Page 555: 6 forms
Page 556: 6 forms
Page 557: 6 forms
Page 558: 6 forms
Page 559: 6 forms
Page 560: 6 forms
Page 561: 6 forms
Page 562: 6 forms
Page 563: 6 forms
Page 564: 6 forms
Page 565: 6 forms
Page 566: 6 forms
Page 567: 6 forms
Page 568: 6 forms
Page 569: 6 forms
Page 570: 6 forms
Page 571: 6 forms
Page 572: 6 forms
Page 573: 6 forms
Page 574: 6 forms
Page 575: 6 forms
Page 576: 6 forms
Page 577: 6 forms
Page 578: 6 forms
Page 579: 6 forms
Page 580: 6 forms
Page 581: 6 forms
Page 582: 6 forms
Page 583: 6 forms
Page 584: 6 forms
Page 585: 6 forms
Page 586: 6 forms
Page 587: 6 forms
Page 588: 6 forms
Page 589: 6 forms
Page 590: 6 forms
Page 591: 6 forms
Page 592: 6 forms
Page 593: 6 forms
Page 594: 6 forms
Page 595: 6 forms
Page 596: 6 forms
Page 597: 6 forms
Page 598: 6 forms
Page 599: 6 forms
Page 600: 6 forms
Page 601: 6 forms
Page 602: 6 forms
Page 603: 6 forms
Page 604: 6 forms
Page 605: 6 forms
Page 606: 6 forms
Page 607: 6 forms
Page 608: 6 forms
Page 609: 6 forms
Page 610: 6 forms
Page 611: 6 forms
Page 612: 6 forms
Page 613: 6 forms
Page 614: 6 forms
Page 615: 6 forms
Page 616: 6 forms
Page 617: 6 forms
Page 618: 6 forms
Page 619: 6 forms
Page 620: 6 forms
Page 621: 6 forms
Page 622: 6 forms
Page 623: 6 forms
Page 624: 6 forms
Page 625: 6 forms
Page 626: 6 forms
Page 627: 6 forms
Page 628: 6 forms
Page 629: 6 forms
Page 630: 6 forms
Page 631: 6 forms
Page 632: 6 forms
Page 633: 6 forms
Page 634: 6 forms
Page 635: 6 forms
Page 636: 6 forms
Page 637: 6 forms
Page 638: 6 forms
Page 639: 6 forms
Page 640: 6 forms
Page 641: 6 forms
Page 642: 6 forms
Page 643: 6 forms
Page 644: 6 forms
Page 645: 6 forms
Page 646: 6 forms
Page 647: 6 forms
Page 648: 6 forms
Page 649: 6 forms
Page 650: 6 forms
Page 651: 6 forms
Page 652: 6 forms
Page 653: 6 forms
Page 654: 6 forms
Page 655: 6 forms
Page 656: 6 forms
Page 657: 6 forms
Page 658: 6 forms
Page 659: 6 forms
Page 660: 6 forms
Page 661: 6 forms
Page 662: 6 forms
Page 663: 6 forms
Page 664: 6 forms
Page 665: 6 forms
Page 666: 6 forms
Page 667: 6 forms
Page 668: 6 forms
Page 669: 6 forms
Page 670: 6 forms
Page 671: 6 forms
Page 672: 6 forms
Page 673: 6 forms
Page 674: 6 forms
Page 675: 6 forms
Page 676: 6 forms
Page 677: 6 forms
Page 678: 6 forms
Page 679: 6 forms
Page 680: 6 forms
Page 681: 6 forms
Page 682: 6 forms
Page 683: 6 forms
Page 684: 6 forms
Page 685: 6 forms
Page 686: 6 forms
Page 687: 6 forms
Page 688: 6 forms
Page 689: 6 forms
Page 690: 6 forms
Page 691: 6 forms
Page 692: 6 forms
Page 693: 6 forms
Page 694: 6 forms
Page 695: 6 forms
Page 696: 6 forms
Page 697: 6 forms
Page 698: 6 forms
Page 699: 6 forms
Page 700: 6 forms
Page 701: 6 forms
Page 702: 6 forms
Page 703: 6 forms
Page 704: 6 forms
Page 705: 6 forms
Page 706: 6 forms
Page 707: 6 forms
Page 708: 6 forms
Page 709: 6 forms
Page 710: 6 forms
Page 711: 6 forms
Page 712: 6 forms
Page 713: 6 forms
Page 714: 6 forms
Page 715: 6 forms
Page 716: 6 forms
Page 717: 6 forms
Page 718: 6 forms
Page 719: 6 forms
Page 720: 6 forms
Page 721: 6 forms
Page 722: 6 forms
Page 723: 6 forms
Page 724: 6 forms
Page 725: 6 forms
Page 726: 6 forms
Page 727: 6 forms
Page 728: 6 forms
Page 729: 6 forms
Page 730: 6 forms
Page 731: 6 forms
Page 732: 6 forms
Page 733: 6 forms
Page 734: 6 forms
Page 735: 6 forms
Page 736: 6 forms
Page 737: 6 forms
Page 738: 6 forms
Page 739: 6 forms
Page 740: 6 forms
Page 741: 6 forms
Page 742: 6 forms
Page 743: 6 forms
Page 744: 6 forms
Page 745: 6 forms
Page 746: 6 forms
Page 747: 6 forms
Page 748: 6 forms
Page 749: 6 forms
Page 750: 6 forms
Page 751: 6 forms
Page 752: 6 forms
Page 753: 6 forms
Page 754: 6 forms
Page 755: 6 forms
Page 756: 6 forms
Page 757: 6 forms
Page 758: 6 forms
Page 759: 6 forms
Page 760: 6 forms
Page 761: 6 forms
Page 762: 6 forms
Page 763: 6 forms
Page 764: 6 forms
Page 765: 6 forms
Page 766: 6 forms
Page 767: 6 forms
Page 768: 6 forms
Page 769: 6 forms
Page 770: 6 forms
Page 771: 6 forms
Page 772: 6 forms
Page 773: 6 forms
Page 774: 6 forms
Page 775: 6 forms
Page 776: 6 forms
Page 777: 6 forms
Page 778: 6 forms
Page 779: 6 forms
Page 780: 6 forms
Page 781: 6 forms
Page 782: 6 forms
Page 783: 6 forms
Page 784: 6 forms
Page 785: 6 forms
Page 786: 6 forms
Page 787: 6 forms
Page 788: 6 forms
Page 789: 6 forms
Page 790: 6 forms
Page 791: 6 forms
Page 792: 6 forms
Page 793: 6 forms
Page 794: 6 forms
Page 795: 6 forms
Page 796: 6 forms
Page 797: 6 forms
Page 798: 6 forms
Page 799: 6 forms
Page 800: 6 forms
Page 801: 6 forms
Page 802: 6 forms
Page 803: 6 forms
Page 804: 6 forms
Page 805: 6 forms
Page 806: 6 forms
Page 807: 6 forms
Page 808: 6 forms
Page 809: 6 forms
Page 810: 6 forms
Page 811: 6 forms
Page 812: 6 forms
Page 813: 6 forms
Page 814: 6 forms
Page 815: 6 forms
Page 816: 6 forms
Page 817: 6 forms
Page 818: 6 forms
Page 819: 6 forms
Page 820: 6 forms
Page 821: 6 forms
Page 822: 6 forms
Page 823: 6 forms
Page 824: 6 forms
Page 825: 6 forms
Page 826: 6 forms
Page 827: 6 forms
Page 828: 6 forms
Page 829: 6 forms
Page 830: 6 forms
Page 831: 6 forms
Page 832: 6 forms
Page 833: 6 forms
Page 834: 6 forms
Page 835: 6 forms
Page 836: 6 forms
Page 837: 6 forms
Page 838: 6 forms
Page 839: 6 forms
Page 840: 6 forms
Page 841: 6 forms
Page 842: 6 forms
Page 843: 6 forms
Page 844: 6 forms
Page 845: 6 forms
Page 846: 6 forms
Page 847: 6 forms
Page 848: 6 forms
Page 849: 6 forms
Page 850: 6 forms
Page 851: 6 forms
Page 852: 6 forms
Page 853: 6 forms
Page 854: 6 forms
Page 855: 6 forms
Page 856: 6 forms
Page 857: 6 forms
Page 858: 6 forms
Page 859: 6 forms
Page 860: 6 forms
Page 861: 6 forms
Page 862: 6 forms
Page 863: 6 forms
Page 864: 6 forms
Page 865: 6 forms

KeyboardInterrupt:

In [ ]:
for form in dmv_forms[:10]:
    print(form)

https://www.dmv.ca.gov/portal/form/language-access-complaint-form-tagalog-adm-140/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-spanish-adm-140sp/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-punjabi-adm-14/
https://www.dmv.ca.gov/portal/form/bill-of-sale-reg-135-pdf/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-armenian-adm-140/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-farsi-adm-140-fa/
https://www.dmv.ca.gov/portal/form/application-for-replacement-plates-stickers-documents-reg-156/
https://www.dmv.ca.gov/portal/form/application-for-replacement-or-transfer-of-title-reg-227/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-russian-adm-140-ru/
https://www.dmv.ca.gov/portal/form/language-access-complaint-form-vietnamese-adm-140/

In [ ]:
def get_dmv_form_links():

    all_forms = set()

    for page in range(1, 32):

        if page == 1:
            url = FORMS_URL
        else:
            url = f"{FORMS_URL}page/{page}/"

        response = requests.get(url)

        soup = BeautifulSoup(response.text, "html.parser")

        page_forms = []

        for a in soup.find_all("a", href=True):

            href = a["href"]

            full_url = urljoin(BASE_URL, href)

            if "/portal/form/" in full_url:
                page_forms.append(full_url)

        page_forms = list(set(page_forms))

        print(f"Page {page}: {len(page_forms)} forms")

        all_forms.update(page_forms)

    return sorted(all_forms)

In [ ]:
dmv_forms = get_dmv_form_links()

print("Total:", len(dmv_forms))

Page 1: 16 forms
Page 2: 16 forms
Page 3: 16 forms
Page 4: 16 forms
Page 5: 16 forms
Page 6: 15 forms
Page 7: 16 forms
Page 8: 16 forms
Page 9: 16 forms
Page 10: 16 forms
Page 11: 16 forms
Page 12: 16 forms
Page 13: 16 forms
Page 14: 16 forms
Page 15: 16 forms
Page 16: 16 forms
Page 17: 16 forms
Page 18: 16 forms
Page 19: 16 forms
Page 20: 16 forms
Page 21: 16 forms
Page 22: 16 forms
Page 23: 15 forms
Page 24: 14 forms
Page 25: 14 forms
Page 26: 15 forms
Page 27: 16 forms
Page 28: 16 forms
Page 29: 16 forms
Page 30: 16 forms
Page 31: 12 forms
Total: 305

## Identify Downloadable PDF Documents
I found that not every discovered page is a downloadable form. So this checks each page to see wether it has a PDF so that only valid files are included in the dataset

In [ ]:
def check_pdf_links(form_links):

    pdf_links = []

    for url in form_links:

        response = requests.get(url)

        content_type = response.headers.get("Content-Type","")

        if "application/pdf" in content_type:
            pdf_links.append(url)

    return pdf_links


dmv_pdf_links = check_pdf_links(dmv_forms)

print("PDFs:", len(dmv_pdf_links))

PDFs: 304

In [ ]:
for url in dmv_pdf_links[:20]:
    print(url)

https://www.dmv.ca.gov/portal/form/10-year-history-record-check-dl-939/
https://www.dmv.ca.gov/portal/form/10-year-history-record-check-spanish-dl-939-sp/
https://www.dmv.ca.gov/portal/form/287903/
https://www.dmv.ca.gov/portal/form/31099/
https://www.dmv.ca.gov/portal/form/34114/
https://www.dmv.ca.gov/portal/form/41965/
https://www.dmv.ca.gov/portal/form/50000-bond-exemption-application-ol-56/
https://www.dmv.ca.gov/portal/form/91495/
https://www.dmv.ca.gov/portal/form/abandoned-vehicle-application-for-salvage-certificate-or-nonrepairable-vehicle-certificate-reg-479/
https://www.dmv.ca.gov/portal/form/affidavit-for-transfer-without-probate-california-titled-vehicle-or-vessels-only-reg-5/
https://www.dmv.ca.gov/portal/form/affidavit-of-non-use-reg-5090/
https://www.dmv.ca.gov/portal/form/agreement-to-prepare-and-maintain-records-in-accordance-with-international-registration-plan-and-california-apportionment-requirements-mc-522-i/
https://www.dmv.ca.gov/portal/form/annual-report-of-autonomous-vehicle-disengagement-ol-311r/
https://www.dmv.ca.gov/portal/form/application-for-approval-of-mature-driver-improvement-course-ol-1002/
https://www.dmv.ca.gov/portal/form/application-for-authorization-for-lien-sale-of-a-lien-sale-for-a-vehicle-valued-over-4000-reg-656/
https://www.dmv.ca.gov/portal/form/application-for-authorization-to-continue-lien-sale-after-unsuccessful-service-reg-659/
https://www.dmv.ca.gov/portal/form/application-for-authorization-to-issue-student-license-ol-804/
https://www.dmv.ca.gov/portal/form/application-for-boat-registration-number-dealer-manufacturer-boat-101a/
https://www.dmv.ca.gov/portal/form/application-for-certification-of-ignition-interlock-device-dl-9/
https://www.dmv.ca.gov/portal/form/application-for-clean-air-vehicle-decals-reg-1000/

In [ ]:
from collections import Counter

extensions = Counter()

for url in dmv_pdf_links:
    filename = url.split("/")[-1]
    extensions[filename.split("-")[0]] += 1

extensions.most_common(20)

[('', 304)]

## Filter the Dataset
The translated form versions are removed so that we collect usable data.

In [ ]:
exclude_words = [
    "spanish",
    "chinese",
    "armenian",
    "farsi",
    "punjabi",
    "russian",
    "tagalog",
    "vietnamese",
    "korean"
]


filtered_dmv_links = [
    url for url in dmv_pdf_links
    if not any(word in url.lower() for word in exclude_words)
]


print("Before:", len(dmv_pdf_links))
print("After:", len(filtered_dmv_links))

Before: 304
After: 278

## Download DMV Documents

In [ ]:
import os
import requests
from pathlib import Path


# Create output directory
dmv_dir = Path("dmv_pdfs")
dmv_dir.mkdir(exist_ok=True)


downloaded_files = []
failed_downloads = []


for i, url in enumerate(filtered_dmv_links, start=1):

    try:
        response = requests.get(url, timeout=30)
        response.raise_for_status()

        # Get filename from URL slug
        filename = url.rstrip("/").split("/")[-1] + ".pdf"

        file_path = dmv_dir / filename

        with open(file_path, "wb") as f:
            f.write(response.content)

        downloaded_files.append(str(file_path))

        print(f"{i}/{len(filtered_dmv_links)} downloaded: {filename}")

    except Exception as e:
        failed_downloads.append((url, str(e)))
        print(f"FAILED: {url}")
        print(e)


print("\nDownload complete")
print("Downloaded:", len(downloaded_files))
print("Failed:", len(failed_downloads))

1/278 downloaded: 10-year-history-record-check-dl-939.pdf
2/278 downloaded: 287903.pdf
3/278 downloaded: 31099.pdf
4/278 downloaded: 34114.pdf
5/278 downloaded: 41965.pdf
6/278 downloaded: 50000-bond-exemption-application-ol-56.pdf
7/278 downloaded: 91495.pdf
8/278 downloaded: abandoned-vehicle-application-for-salvage-certificate-or-nonrepairable-vehicle-certificate-reg-479.pdf
9/278 downloaded: affidavit-for-transfer-without-probate-california-titled-vehicle-or-vessels-only-reg-5.pdf
10/278 downloaded: affidavit-of-non-use-reg-5090.pdf
11/278 downloaded: agreement-to-prepare-and-maintain-records-in-accordance-with-international-registration-plan-and-california-apportionment-requirements-mc-522-i.pdf
12/278 downloaded: annual-report-of-autonomous-vehicle-disengagement-ol-311r.pdf
13/278 downloaded: application-for-approval-of-mature-driver-improvement-course-ol-1002.pdf
14/278 downloaded: application-for-authorization-for-lien-sale-of-a-lien-sale-for-a-vehicle-valued-over-4000-reg-656.pdf
15/278 downloaded: application-for-authorization-to-continue-lien-sale-after-unsuccessful-service-reg-659.pdf
16/278 downloaded: application-for-authorization-to-issue-student-license-ol-804.pdf
17/278 downloaded: application-for-boat-registration-number-dealer-manufacturer-boat-101a.pdf
18/278 downloaded: application-for-certification-of-ignition-interlock-device-dl-9.pdf
19/278 downloaded: application-for-clean-air-vehicle-decals-reg-1000.pdf
20/278 downloaded: application-for-critical-need-restrisction-ds-694.pdf
21/278 downloaded: application-for-disabled-person-placard-or-plates-reg-195.pdf
22/278 downloaded: application-for-junior-permit-dl-120.pdf
23/278 downloaded: application-for-lien-sale-authorization-and-lienholders-certification-vessel-or-vessel-trailer-valued-over-1500.pdf
24/278 downloaded: application-for-modification-to-a-traffic-violator-school-license-ol-736.pdf
25/278 downloaded: application-for-modification-to-a-traffic-violator-school-operator-and-instructor-license-ol-711-pdf.pdf
26/278 downloaded: application-for-non-commercial-restricted-driver-license-for-financial-responsibility-actions-dl-691.pdf
27/278 downloaded: application-for-permanent-disabled-person-dp-placard-renewal-reg-195a.pdf
28/278 downloaded: application-for-permit-to-deploy-autonomous-vehicles-ol321-on-public-streets.pdf
29/278 downloaded: application-for-refund-adm-399.pdf
30/278 downloaded: application-for-renewal-of-traffic-violator-school-tvs-instructor-license-ol-740.pdf
31/278 downloaded: application-for-renewal-of-traffic-violator-school-tvs-operator-license-ol-756.pdf
32/278 downloaded: application-for-replacement-or-transfer-of-title-reg-227.pdf
33/278 downloaded: application-for-replacement-or-transfer-vessel-title.pdf
34/278 downloaded: application-for-replacement-plates-stickers-documents-reg-156-sp.pdf
35/278 downloaded: application-for-replacement-plates-stickers-documents-reg-156.pdf
36/278 downloaded: application-for-return-of-non-resident-plates-reg-356.pdf
37/278 downloaded: application-for-salvage-certificate-or-nonrepairable-vehicle-certificate-reg-488c.pdf
38/278 downloaded: application-for-special-equipment-identification-plate-reg-88.pdf
39/278 downloaded: application-for-special-identification-plate-dealer-manufacturer-reg-353.pdf
40/278 downloaded: application-for-special-motorcycle-transportation-permit-reg-712.pdf
41/278 downloaded: application-for-temporary-registration-nonresident-commercial-vehicle-reg-471.pdf
42/278 downloaded: application-for-temporary-smog-exemption-for-a-vehicle-located-out-of-state-reg-5103.pdf
43/278 downloaded: application-for-termination-of-action-dl-4006.pdf
44/278 downloaded: application-for-title-or-registration-verification-of-vehicle-reg-343.pdf
45/278 downloaded: application-for-traffic-violator-school-operator-and-instructor-license-ol-710-pdf.pdf
46/278 downloaded: application-for-traffic-violator-school-tvs-owner-license-part-a-ol-713.pdf
47/278 downloaded: application-for-tvs-administrator-change-ol-757.pdf
48/278 downloaded: application-for-vehicle-license-fee-refund-reg-65.pdf
49/278 downloaded: application-for-vessel-certificate-of-number-boat-101.pdf
50/278 downloaded: appointment-of-director-as-agent-for-service-of-process-adm-9050.pdf
51/278 downloaded: arizona-reduced-fee-certification-mc-2132-i.pdf
52/278 downloaded: attorneys-information-request-vehicle-vessel-related-incidents-only-inf-1161e.pdf
53/278 downloaded: authorization-for-release-of-driver-record-information-inf-1101.pdf
54/278 downloaded: authorization-requisition-for-driver-instruction-forms-dl-396.pdf
55/278 downloaded: authorization-to-release-financial-information-ol-53.pdf
56/278 downloaded: autonomous-vehicle-deployment-checklist-ol-321c.pdf
57/278 downloaded: autonomous-vehicle-deployment-permit-application-for-certificate-of-self-insurance.pdf
58/278 downloaded: autonomous-vehicle-manufacturer-surety-bond-ol-317.pdf
59/278 downloaded: autonomous-vehicle-tester-avt-program-application-for-certificate-of-self-insurance-ol-319.pdf
60/278 downloaded: autonomous-vehicle-tester-avt-program-application-for-manufacturers-testing-permit-driverless-vehicles-ol-318.pdf
61/278 downloaded: bill-of-sale-reg-135-pdf.pdf
62/278 downloaded: business-partner-automation-application-first-line-service-provider-reg-4024.pdf
63/278 downloaded: business-partner-automation-application-second-line-business-partner-reg-4025.pdf
64/278 downloaded: business-partner-automation-program-application-for-changes-reg-4026.pdf
65/278 downloaded: business-partner-automation-program-information-security-pre-implementation-checklist-exec-5555b.pdf
66/278 downloaded: business-partner-automation-program-representative-non-disclosure-statement-reg-4028.pdf
67/278 downloaded: business-partner-automation-program-service-provider-change-reg-4022.pdf
68/278 downloaded: business-partner-automation-renewal-application-reg-5056.pdf
69/278 downloaded: business-partner-deposit-agreement-and-assignment-reg-4029.pdf
70/278 downloaded: california-commercial-driver-behind-the-wheel-training-certification-dl-1236.pdf
71/278 downloaded: california-commercial-driver-license-self-certification-form-dl-694.pdf
72/278 downloaded: california-driver-license-renewal-by-mail-eligibility-information-dl-410-fo.pdf
73/278 downloaded: california-identification-card-renewal-by-mail-eligibility-dl-410-id.pdf
74/278 downloaded: california-identification-card-renewal-by-mail-eligibility.pdf
75/278 downloaded: california-irp-vehicle-data-schedule-c-mc-2118i.pdf
76/278 downloaded: cdl-test-waiver-for-military-members-dl-965-pdf.pdf
77/278 downloaded: certificate-of-facts-re-unsatisfied-judgment.pdf
78/278 downloaded: certificate-of-insurance-irp-or-pfr-mc-5009-i.pdf
79/278 downloaded: certificate-of-repossession-reg-119.pdf
80/278 downloaded: certification-for-disabled-veterans-license-plates-reg-256v.pdf
81/278 downloaded: certification-of-agency-inf-1184.pdf
82/278 downloaded: certification-of-lien-sale-for-vehicle-valued-4000-or-less-reg-168a-pdf.pdf
83/278 downloaded: certification-of-lien-sale-for-vessel-or-vessel-with-trailer-valued-at-1500-or-less-boat-177.pdf
84/278 downloaded: certification-of-lien-sale-for-vessel-or-vessel-with-trailer-valued-over-1500-boat-178.pdf
85/278 downloaded: certification-of-lien-sale-reg-168-pdf.pdf
86/278 downloaded: classroom-branch-renewal-application-ol-737.pdf
87/278 downloaded: commanding-officers-certification-of-driving-experience-dl-964.pdf
88/278 downloaded: commercial-or-government-employer-pull-notice-enrollment-of-out-of-state-licensed-drivers-form-and-instructions-inf-1102.pdf
89/278 downloaded: commercial-requester-account-application-inf-1106.pdf
90/278 downloaded: commercial-requester-account-bond-inf-1132.pdf
91/278 downloaded: commercial-requester-account-instructions-application-inf-1133.pdf
92/278 downloaded: commercial-requester-account-service-provider-application-inf-1106v.pdf
93/278 downloaded: continuing-education-exemption-application-ol-257.pdf
94/278 downloaded: courtesy-stop-request-reg-500.pdf
95/278 downloaded: cuestionario-de-medico-dl-546.pdf
96/278 downloaded: dealer-education-certificate-issuance-log-pre-licensing-ol-4005.pdf
97/278 downloaded: dealer-statement-of-facts-reg-477.pdf
98/278 downloaded: declaration-of-gvw-cgw-reg-4008-pdf.pdf
99/278 downloaded: declaration-regarding-certificate-of-insurance-for-non-resident-driver-dl-300.pdf
100/278 downloaded: disabled-person-or-disabled-veteran-license-plate-certification-form-reg-3060.pdf
101/278 downloaded: dismissal-for-reason-involving-pupil-transportation-safety-dl-128.pdf
102/278 downloaded: dmv-pre-employment-behavior-standards-questionnaire.pdf
103/278 downloaded: driver-education-driver-training-completion-certificate-log-dl-803.pdf
104/278 downloaded: driver-license-record-correction-request-dl-207.pdf
105/278 downloaded: driving-performance-evaluation-score-sheet-dl-32.pdf
106/278 downloaded: driving-school-application-for-student-license-ol-801.pdf
107/278 downloaded: driving-under-the-influence-internet-program-forms-systems-dl-947.pdf
108/278 downloaded: ds-334.pdf
109/278 downloaded: dui-program-signatory-authority-dl-101s.pdf
110/278 downloaded: eeo-discrimination-complaint-confidential-exec-50.pdf
111/278 downloaded: employer-pull-notice-agent-authorization-form-inf-2110.pdf
112/278 downloaded: employer-testing-program-agreement-dl-520b-etp.pdf
113/278 downloaded: employer-testing-program-application-for-employer-number-dl-520-etp.pdf
114/278 downloaded: employer-testing-program-commercial-dpe-maneuver-checklist-dl-807-etp.pdf
115/278 downloaded: employer-testing-program-commercial-driving-performance-evaluation-route-and-directions-dl-814-etp.pdf
116/278 downloaded: employer-testing-program-examiner-certification-application-dl-811-etp.pdf
117/278 downloaded: employer-testing-program-request-for-reactivation-employer-number-dl-817-etp.pdf
118/278 downloaded: employer-testing-program-surety-bond-dl-524-etp.pdf
119/278 downloaded: employer-testing-program-voluntary-cancellation-request-dl-520c-etp.pdf
120/278 downloaded: employers-report-of-medical-exam-failure-request-for-reexamination-ds-524.pdf
121/278 downloaded: enrollment-application-tvs-court-primary-administrator-traffic-violator-course-completion-database-ol-771.pdf
122/278 downloaded: external-account-and-role-request-dl-950.pdf
123/278 downloaded: financial-responsibility-information-request-sr-19c.pdf
124/278 downloaded: foreign-resident-in-transit-permit-application-reg-34-drm.pdf
125/278 downloaded: health-questionnaire-dl-546.pdf
126/278 downloaded: historical-vessel-plaque.pdf
127/278 downloaded: ignition-interlock-device-exemption-request-dl-4062-pdf.pdf
128/278 downloaded: ignition-interlock-device-iid-installation-and-removal-request-dl-925.pdf
129/278 downloaded: ignition-interlock-device-iid-medical-exemption-request-dl-4063.pdf
130/278 downloaded: industry-customer-employee-listing-fo-607a.pdf
131/278 downloaded: industry-holdout-correction-request-fax-transmission-sheet-fo-31.pdf
132/278 downloaded: information-request-motor-carrier-permit-mc-430-m.pdf
133/278 downloaded: information-security-and-disclosure-statement-firm-exec-201x.pdf
134/278 downloaded: information-security-and-disclosure-statement-public-private-partnerships-employee-exec-200x.pdf
135/278 downloaded: information-security-statement-inf-1128.pdf
136/278 downloaded: information-services-program-agent-authorization-inf-03.pdf
137/278 downloaded: instructions-for-vehicle-verifier-ol-89.pdf
138/278 downloaded: internal-account-and-role-request-dl-949.pdf
139/278 downloaded: internet-security-agreement-certification-dadp-provider-administrator-dl-952.pdf
140/278 downloaded: internet-security-agreement-certification-dadp-representative-dl-951.pdf
141/278 downloaded: internet-security-agreement-certification-program-provider-administrator-dl-945.pdf
142/278 downloaded: internet-security-agreement-certification-program-provider-representative-dl-946.pdf
143/278 downloaded: laboratory-report-dl-28.pdf
144/278 downloaded: language-access-complaint-form-english-adm-140.pdf
145/278 downloaded: lien-satisfied-title-holder-release-reg-166.pdf
FAILED: https://www.dmv.ca.gov/portal/form/mature-driver-completion-certificate-order-form-ol-1005/
HTTPSConnectionPool(host='www.dmv.ca.gov', port=443): Read timed out. (read timeout=30)
147/278 downloaded: misuse-of-record-information-complaint-inf-1164.pdf
148/278 downloaded: motor-carrier-fleet-name-change-mc-256m-i.pdf
149/278 downloaded: motor-carrier-permit-application-for-certificate-of-self-insurance-dmv-130-mcp.pdf
150/278 downloaded: motor-carrier-permit-application-instruction-dmv-706.pdf
151/278 downloaded: motor-carrier-permit-notice-of-change-mc-152-m.pdf
152/278 downloaded: motor-vehicle-ownership-surety-bond-reg-5057.pdf
153/278 downloaded: motorized-bicycle-instructions-application-reg-230.pdf
154/278 downloaded: new-clean-air-vehicle-decal-application-form-vr-2018-27.pdf
155/278 downloaded: non-repairable-vehicle-notice-of-retention-by-owner-reg-480.pdf
156/278 downloaded: nonresident-military-nrm-exemption-statement-reg-5045.pdf
157/278 downloaded: north-atlantic-treaty-organization-nato-status-of-forces-agreement-reg-5046.pdf
158/278 downloaded: notice-of-change-of-address.pdf
159/278 downloaded: notice-of-intent-to-dispose-of-a-vehicle-valued-500-or-less-removed-by-a-public-agency-for-reasons-other-than-abandonment-reg-684.pdf
160/278 downloaded: notice-of-non-compliance-ignition-interlock-dl-921.pdf
161/278 downloaded: notice-of-pending-lien-sale-for-vehicle-valued-4000-or-less.pdf
162/278 downloaded: notice-of-pending-lien-sale-for-vessels-or-vessel-trailers-valued-at-1500-or-less-boat-156-2.pdf
163/278 downloaded: notice-of-pending-lien-sale-for-vessels-or-vessel-trailers-valued-at-1500-or-less-boat-156.pdf
164/278 downloaded: notice-of-pending-lien-sale-of-vehicle-valued-over-4000-or-from-a-self-service-storage-facility-reg-280.pdf
165/278 downloaded: notice-of-transfer-and-release-of-liability-reg-138.pdf
166/278 downloaded: notice-of-unsatisfied-judgment-of-1000-or-less-dl-17.pdf
167/278 downloaded: notice-removal-of-abandoned-vehicle-reg-104.pdf
168/278 downloaded: notice-to-employers-ignition-interlock-restriction-dl-923-pdf.pdf
169/278 downloaded: notificacion-de-cambio-certificado-de-transportista-privado-de-pasajeros-reg-1301-sp.pdf
170/278 downloaded: notification-of-alternative-forms-of-financial-responsibility-reg-5085.pdf
171/278 downloaded: notification-of-class-schedule-ol-854e.pdf
172/278 downloaded: occupational-license-notice-of-cancellation-ol-4007.pdf
173/278 downloaded: occupational-license-notice-of-reinstatement-ol-4008.pdf
174/278 downloaded: occupational-licensing-section-notification-of-commercial-skills-test-schedule-ol-810.pdf
175/278 downloaded: occupational-licensing-statement-of-facts.pdf
176/278 downloaded: official-classroom-location-schedule-ol-854.pdf
177/278 downloaded: official-school-class-cancellation-for-standard-emergency-notification-ol-749.pdf
178/278 downloaded: ol-400.pdf
179/278 downloaded: ol-4004.pdf
180/278 downloaded: order-request-reduced-fee-or-no-fee-identification-card-program-dl-932.pdf
181/278 downloaded: outline-of-required-topics-and-standards-for-ca-dmv-approved-traffic-violator-school-course-ol-613.pdf
182/278 downloaded: participants-certification-of-dui-program-enrollment-or-completion-dl-804.pdf
183/278 downloaded: permanent-fleet-registration-addition-deletion-mc-495-p.pdf
184/278 downloaded: permanent-trailer-identification-certification-reg-4017.pdf
185/278 downloaded: pfr-authorization-signature-form-mc-3501-p.pdf
186/278 downloaded: physicians-health-report-dl-546a.pdf
187/278 downloaded: postal-service-verification-of-no-mail-delivery-service-or-change-of-address-ol-4000.pdf
188/278 downloaded: power-of-attorney-reg-260-pdf.pdf
189/278 downloaded: private-secondary-non-classroom-driver-education-curriculum-certification-dl-396b.pdf
190/278 downloaded: property-use-verification-for-a-driving-school-or-traffic-violator-school-license-ol-140.pdf
191/278 downloaded: property-use-verification-for-registration-service-license-ol-139.pdf
192/278 downloaded: provider-dui-program-administrator-designee-document-dl-948.pdf
193/278 downloaded: quarterly-physical-inventory-boat-124.pdf
194/278 downloaded: refresher-training-request-dl-818-etp.pdf
195/278 downloaded: registration-information-request-for-lien-sale-inf-1126.pdf
196/278 downloaded: renewal-list.pdf
197/278 downloaded: report-of-traffic-accident-occurring-in-california.pdf
198/278 downloaded: report-of-traffic-collision-involving-an-autonomous-vehicle-ol-316.pdf
199/278 downloaded: report-of-vision-examination-dl-62.pdf
200/278 downloaded: report-out-of-state-traffic-conviction-by-a-commercial-driver-dl-535.pdf
201/278 downloaded: request-for-approval-of-tvs-educational-program-ol-764.pdf
202/278 downloaded: request-for-approval-of-tvs-operator-educational-training-program-ol-765.pdf
203/278 downloaded: request-for-cancellation-or-surrender-of-a-driver-license-or-identification-card-dl-142.pdf
204/278 downloaded: request-for-closure-of-employer-pull-notice-account-form-and-instructions-inf-1112.pdf
205/278 downloaded: request-for-dismissal-of-failure-to-appear-fta-violations-dl-114.pdf
206/278 downloaded: request-for-driver-license-identification-card-status-and-record-information-inf-1119.pdf
207/278 downloaded: request-for-driver-reexamination-ds-699-sp-pdf.pdf
208/278 downloaded: request-for-driver-reexamination-ds-699.pdf
209/278 downloaded: request-for-dui-program-forms-dl-101r.pdf
210/278 downloaded: request-for-live-scan-service-applicant-submission-dmv-8016.pdf
211/278 downloaded: request-for-national-driver-register-ndr-file-check-on-current-or-prospective-employee-inf-1301a.pdf
212/278 downloaded: request-for-record-information-web-only-inf-70.pdf
213/278 downloaded: request-for-use-of-an-approved-tvs-program-ol-766.pdf
214/278 downloaded: request-for-vehicle-vessel-automated-record-information-inf-1123.pdf
215/278 downloaded: request-for-vehicle-vessel-photo-history-information-inf-1124.pdf
216/278 downloaded: request-for-voluntary-termination-of-motor-carrier-permit-certificate-of-self-insurance-mc-132-m.pdf
217/278 downloaded: request-for-voluntary-withdrawal-motor-carrier-permit-mc-716-m.pdf
218/278 downloaded: request-for-voluntary-withdrawal-private-carrier-of-passengers-certificate-reg-1308.pdf
219/278 downloaded: request-for-your-own-driver-license-identification-card-or-vehicle-vessel-registration-information-record-inf-1125.pdf
220/278 downloaded: revised-miscellaneous-certifications-reg-256a.pdf
221/278 downloaded: salesperson-license-renewal-application.pdf
222/278 downloaded: salvage-vehicle-notice-of-retention-by-owner-reg-481.pdf
223/278 downloaded: sample-license-plate-order-form-reg-580.pdf
224/278 downloaded: sample-license-plates-now-available-vin-2018-15.pdf
225/278 downloaded: school-bus-registration-or-permit-application-reg-123.pdf
226/278 downloaded: self-referral-for-reevaluation-of-driving-skill-ds-699a.pdf
227/278 downloaded: solicitud-para-obtener-el-certificado-de-transportista-privado-de-pasajeros-reg-1300.pdf
228/278 downloaded: special-interest-license-plates-application-reg-17.pdf
229/278 downloaded: special-recognition-license-plate-application-reg-17a.pdf
230/278 downloaded: specialized-transportation-vehicle-exemption-certification-reg-345.pdf
231/278 downloaded: state-agency-sponsored-specialized-license-plate-application-reg-5102.pdf
232/278 downloaded: statement-of-consent-to-issue-an-acceptance-of-liability-for-a-student-license-dl-119.pdf
233/278 downloaded: statement-of-construction-reg-5036.pdf
234/278 downloaded: statement-of-facts-california-non-certified-vehicle-reg-256f.pdf
235/278 downloaded: statement-of-facts-for-vehicles-valuated-at-500-or-less-removed-by-a-public-agency-for-reasons-other-than-abandonment-reg-686.pdf

In [ ]:
list(dmv_dir.iterdir())[:10]

[PosixPath('dmv_pdfs/statement-of-multiple-county-use-of-vehicle-reg-6004.pdf'),
 PosixPath('dmv_pdfs/traffic-violator-school-foreign-language-approval-request.pdf'),
 PosixPath('dmv_pdfs/motorized-bicycle-instructions-application-reg-230.pdf'),
 PosixPath('dmv_pdfs/request-for-vehicle-vessel-automated-record-information-inf-1123.pdf'),
 PosixPath('dmv_pdfs/renewal-list.pdf'),
 PosixPath('dmv_pdfs/traffic-violator-school-branch-business-office-classroom-application-ol-712-pdf.pdf'),
 PosixPath('dmv_pdfs/notification-of-class-schedule-ol-854e.pdf'),
 PosixPath('dmv_pdfs/notice-of-change-of-address.pdf'),
 PosixPath('dmv_pdfs/salvage-vehicle-notice-of-retention-by-owner-reg-481.pdf'),
 PosixPath('dmv_pdfs/notice-of-intent-to-dispose-of-a-vehicle-valued-500-or-less-removed-by-a-public-agency-for-reasons-other-than-abandonment-reg-684.pdf')]

In [ ]:
from pathlib import Path
!pip install PyMuPDF
import fitz  # PyMuPDF


sample = list(dmv_dir.glob("*.pdf"))[0]

doc = fitz.open(sample)

text = ""

for page in doc:
    text += page.get_text()

print(sample.name)
print(text[:500])

Collecting PyMuPDF
  Downloading pymupdf-1.28.0-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (26 kB)
Downloading pymupdf-1.28.0-cp310-abi3-manylinux_2_28_x86_64.whl (25.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.7/25.7 MB 54.9 MB/s eta 0:00:00
Installing collected packages: PyMuPDF
Successfully installed PyMuPDF-1.28.0
statement-of-multiple-county-use-of-vehicle-reg-6004.pdf

































STATEMENT OF MULTIPLE COUNTY USE OF VEHICLE
(CVC §4004.5)
MAIL TO DEPARTMENT OF MOTOR VEHICLES
P.O. BOX 942869
 SACRAMENTO, CA 94269-0001
YOU MAY PROVIDE THE FOLLOWING INFORMATION IF YOU RESIDE IN MORE THAN ONE COUNTY FOR
A PERIOD OF MORE THAN 30 DAYS, OR USE YOUR VEHICLE IN A COUNTY OTHER THAN YOUR COUNTY
OF LEGAL RESIDENCE FOR BUSINESS PURPOSES. ADDITIONAL PAGES MAY BE ATTACHED IF THE
INFORMATION TO BE SUBMITTED EXCEED

## Generate Document Metadata
Metadata is created for each PDF, like file name, agency, form identifier, doc type, and file location. This is helpful when I later combine the data.

In [ ]:
import os
import pandas as pd
from pathlib import Path


def build_metadata(folder, agency):
    records = []

    for file in Path(folder).glob("*.pdf"):
        records.append({
            "filename": file.name,
            "filepath": str(file),
            "agency": agency
        })

    return records


uscis_records = build_metadata(
    "uscis_pdfs",
    "USCIS"
)

dmv_records = build_metadata(
    "dmv_pdfs",
    "DMV"
)


documents = pd.DataFrame(
    uscis_records + dmv_records
)


documents.head()

,filename,filepath,agency
0,statement-of-multiple-county-use-of-vehicle-re...,dmv_pdfs/statement-of-multiple-county-use-of-v...,DMV
1,traffic-violator-school-foreign-language-appro...,dmv_pdfs/traffic-violator-school-foreign-langu...,DMV
2,motorized-bicycle-instructions-application-reg...,dmv_pdfs/motorized-bicycle-instructions-applic...,DMV
3,request-for-vehicle-vessel-automated-record-in...,dmv_pdfs/request-for-vehicle-vessel-automated-...,DMV
4,renewal-list.pdf,dmv_pdfs/renewal-list.pdf,DMV

In [ ]:
documents["agency"].value_counts()

agency
DMV    277
Name: count, dtype: int64

In [ ]:
from pathlib import Path

print("DMV PDFs:", len(list(Path("dmv_pdfs").glob("*.pdf"))))

DMV PDFs: 277

## Export and Save Data

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from pathlib import Path

PROJECT_DIR = Path("/content/drive/MyDrive/newstart_ai")

PROJECT_DIR.mkdir(exist_ok=True)

(PROJECT_DIR / "data/raw").mkdir(parents=True, exist_ok=True)

In [ ]:
import pandas as pd
from pathlib import Path
import re


# Folder where DMV PDFs are stored
dmv_folder = Path("/content/dmv_pdfs")


def extract_dmv_form_number(filename):
    """
    Extract DMV form numbers from filenames.

    Examples:
    reg-227.pdf -> REG-227
    dl-939.pdf -> DL-939
    """

    match = re.search(
        r"(reg|dl|ol|adm|inf|mc)-?\d+",
        filename.lower()
    )

    if match:
        return match.group(0).upper()

    return None



dmv_metadata = []


for pdf in dmv_folder.glob("*.pdf"):

    filename = pdf.name

    dmv_metadata.append({
        "filename": filename,
        "agency": "DMV",
        "form_number": extract_dmv_form_number(filename),
        "document_type": "form",
        "filepath": str(pdf)
    })


dmv_df = pd.DataFrame(dmv_metadata)


# Save CSV
dmv_df.to_csv(
    "dmv_metadata.csv",
    index=False
)


print("DMV metadata saved!")
print("Rows:", len(dmv_df))

dmv_df.head()

DMV metadata saved!
Rows: 277

,filename,agency,form_number,document_type,filepath
0,statement-of-multiple-county-use-of-vehicle-re...,DMV,REG-6004,form,/content/dmv_pdfs/statement-of-multiple-county...
1,traffic-violator-school-foreign-language-appro...,DMV,None,form,/content/dmv_pdfs/traffic-violator-school-fore...
2,motorized-bicycle-instructions-application-reg...,DMV,REG-230,form,/content/dmv_pdfs/motorized-bicycle-instructio...
3,request-for-vehicle-vessel-automated-record-in...,DMV,INF-1123,form,/content/dmv_pdfs/request-for-vehicle-vessel-a...
4,renewal-list.pdf,DMV,None,form,/content/dmv_pdfs/renewal-list.pdf

In [ ]:
import pandas as pd
from pathlib import Path


dmv_folder = Path("/content/drive/MyDrive/newstart_ai/data/raw/dmv")

metadata = []

for pdf in dmv_folder.glob("*.pdf"):

    metadata.append({
        "filename": pdf.name,
        "filepath": str(pdf),
        "agency": "DMV",
        "document_type": "form"
    })


dmv_df = pd.DataFrame(metadata)


output_path = Path(
    "/content/drive/MyDrive/newstart_ai/data/metadata/dmv_metadata.csv"
)

dmv_df.to_csv(output_path, index=False)


print("DMV metadata saved!")
print("Rows:", len(dmv_df))

dmv_df.head()

DMV metadata saved!
Rows: 277

,filename,filepath,agency,document_type
0,statement-of-multiple-county-use-of-vehicle-re...,/content/drive/MyDrive/newstart_ai/data/raw/dm...,DMV,form
1,traffic-violator-school-foreign-language-appro...,/content/drive/MyDrive/newstart_ai/data/raw/dm...,DMV,form
2,motorized-bicycle-instructions-application-reg...,/content/drive/MyDrive/newstart_ai/data/raw/dm...,DMV,form
3,request-for-vehicle-vessel-automated-record-in...,/content/drive/MyDrive/newstart_ai/data/raw/dm...,DMV,form
4,renewal-list.pdf,/content/drive/MyDrive/newstart_ai/data/raw/dm...,DMV,form